//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

RUN_UTILS CopyFile ${SYSDRIVE}\testdata\configs\readwriteConfig.ini ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak
START_TESTCASE DT-TEF-TestStep-0002
//! @SYMTestCaseID          DT-TEF-TestStep-0002
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Negative Test of read/write value from/to configuration file.
//! @SYMTestExpectedResults Test case should be passed.
//! @SYMTestActions         1. Read/write value from/to a section in an ini file
//!                         2. The secion doesn't exist in the ini file
//!                         3. Section name doesn't specify in script file.
//!                         4. Section is empty.
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          1. Under Development
	RUN_TEST_STEP 100 te_RegStepTestSuite ReadWriteConfigNegStep ${SYSDRIVE}\testdata\configs\readwriteconfig.ini Section6
	RUN_TEST_STEP 100 te_RegStepTestSuite ReadWriteConfigNegStep
	RUN_TEST_STEP 100 te_RegStepTestSuite ReadWriteConfigNegStep ${SYSDRIVE}\testdata\configs\readwriteconfig.ini Section8
END_TESTCASE DT-TEF-TestStep-0002

RUN_UTILS DeleteFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
RUN_UTILS CopyFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
RUN_UTILS DeleteFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak
