//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

START_TESTCASE DT-TEF-TestStep-0003
//! @SYMTestCaseID          DT-TEF-TestStep-0003
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test function "SetTestStepResult" and "SetTestStepError" of class "CTestStep".
//! @SYMTestExpectedResults Test case is passed and the error value is as expected.
//! @SYMTestActions         Sets the test step error and check if the error set by test step is as expected.
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          1. Under Development
	RUN_TEST_STEP !Error=-1 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error1
	RUN_TEST_STEP !Error=-2 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error2
	RUN_TEST_STEP !Error=-3 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error3
	RUN_TEST_STEP !Error=-4 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error4
	RUN_TEST_STEP !Error=-5 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error5
	RUN_TEST_STEP !Error=-6 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error6
	RUN_TEST_STEP !Error=-7 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error7
	RUN_TEST_STEP !Error=-8 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error8
	RUN_TEST_STEP !Error=-9 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error9
	RUN_TEST_STEP !Error=-10 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error10
	RUN_TEST_STEP !Error=-11 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error11
	RUN_TEST_STEP !Error=-12 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error12
	RUN_TEST_STEP !Error=-13 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error13
	RUN_TEST_STEP !Error=-14 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error14
	RUN_TEST_STEP !Error=-15 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error15
	RUN_TEST_STEP !Error=-16 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error16
	RUN_TEST_STEP !Error=-17 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error17
	RUN_TEST_STEP !Error=-18 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error18
	RUN_TEST_STEP !Error=-19 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error19
	RUN_TEST_STEP !Error=-20 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error20
	RUN_TEST_STEP !Error=-21 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error21
	RUN_TEST_STEP !Error=-22 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error22
	RUN_TEST_STEP !Error=-23 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error23
	RUN_TEST_STEP !Error=-24 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error24
	RUN_TEST_STEP !Error=-25 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error25
	RUN_TEST_STEP !Error=-26 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error26
	RUN_TEST_STEP !Error=-27 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error27
	RUN_TEST_STEP !Error=-28 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error28
	RUN_TEST_STEP !Error=-29 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error29
	RUN_TEST_STEP !Error=-30 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error30
	RUN_TEST_STEP !Error=-31 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error31
	RUN_TEST_STEP !Error=-32 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error32
	RUN_TEST_STEP !Error=-33 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error33
	RUN_TEST_STEP !Error=-34 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error34
	RUN_TEST_STEP !Error=-35 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error35
	RUN_TEST_STEP !Error=-36 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error36
	RUN_TEST_STEP !Error=-37 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error37
	RUN_TEST_STEP !Error=-38 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error38
	RUN_TEST_STEP !Error=-39 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error39
	RUN_TEST_STEP !Error=-40 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error40
	RUN_TEST_STEP !Error=-41 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error41
	RUN_TEST_STEP !Error=-42 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error42
	RUN_TEST_STEP !Error=-43 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error43
	RUN_TEST_STEP !Error=-44 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error44
	RUN_TEST_STEP !Error=-45 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error45
	RUN_TEST_STEP !Error=-46 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error46
	RUN_TEST_STEP !Error=-47 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error47
	RUN_TEST_STEP !Error=-48 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini Error48
	
	RUN_TEST_STEP !Result=Pass 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini ResultPass
END_TESTCASE DT-TEF-TestStep-0003
