//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

START_TESTCASE DT-TEF-TestStep-0025
//! @SYMTestCaseID          DT-TEF-TestStep-0025
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test function &quot;WriteHexToConfig&quot; of class CTestStep with server -SharedData.
//! @SYMTestExpectedResults A integer in HEX format should be written into script file.
//!                         The test result should be pass.
//! @SYMTestActions         Write a hex value into the configuration file and check the write result.
	RUN_TEST_STEP 100 te_RegStepTestSuite WriteHexStep ${SYSDRIVE}\testdata\configs\WriteToConfig.ini Section0
END_TESTCASE DT-TEF-TestStep-0025
