//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

RUN_UTILS CopyFile ${SYSDRIVE}\testdata\configs\readwriteConfig.ini ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak
START_TESTCASE DT-TEF-TestStep-0021
//! @SYMTestCaseID          DT-TEF-TestStep-0021
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test read and write config value from configuration file with server -SharedData.
//! @SYMTestExpectedResults The information in the config file should be read in and write correctly.
//!                         The test result should be pass.
//! @SYMTestActions         Load a configuration file, read the value from it and write a value into it.
	RUN_TEST_STEP 100 te_RegStepTestSuite ReadWriteConfigStep ${SYSDRIVE}\testdata\configs\readwriteconfig.ini Section0
	RUN_TEST_STEP 100 te_RegStepTestSuite ReadWriteConfigStep ${SYSDRIVE}\testdata\configs\readwriteconfig.ini Section7
END_TESTCASE DT-TEF-TestStep-0021

RUN_UTILS DeleteFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
RUN_UTILS CopyFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
RUN_UTILS DeleteFile ${SYSDRIVE}\testdata\configs\readwriteconfig.ini.bak

