//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

START_TESTCASE DT-TEF-TestStep-0013
//! @SYMTestCaseID          DT-TEF-TestStep-0013
//! @SYMCreationDate        30-07-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test long server name and long step name which exceeds the max length.
//! @SYMTestExpectedResults The test will be failed.
//! @SYMTestActions         1. Run a step which the server name is longer than the max value
//!                         2. Run a step which the step name is longer than the max value
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          2. Functional
	PRINT this case will be passed with the error message cannot create server.
	LOAD_SERVER te_RegStepTestSuiteLonggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
END_TESTCASE DT-TEF-TestStep-0013
