//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

START_TESTCASE DT-TEF-TestStep-0036
//! @SYMTestCaseID          DT-TEF-TestStep-0036
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestType            CT
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        test RUN_TEST_STEP_RESULT with 110 Ignore with server -SharedData.
//! @SYMTestExpectedResults test case should fail
	PRINT this test case should be fail. test setp is unexecute because ignore.  
	RUN_TEST_STEP_RESULT 110 100 te_RegStepTestSuite SetErrorStep ${SYSDRIVE}\testdata\configs\Error_codes.ini ResultIgnore
END_TESTCASE DT-TEF-TestStep-0036
