//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

START_TESTCASE DT-TEF-TestStep-0034
//! @SYMTestCaseID          DT-TEF-TestStep-0034
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test the cases that the server and/or the step name is not correct with server -SharedData.
//! @SYMTestExpectedResults The test will be failed.
//! @SYMTestActions         1. Load a server which is not exist
//!                         2. Run a step which the server is not exist
//!                         3. Run a step which is not exist.
	PRINT This case will be failed.
	LOAD_SERVER te_RegStepTestSuiteNotExist
	RUN_TEST_STEP 100 te_RegStepTestSuiteNotExist ShortFunsStep
	RUN_TEST_STEP 100 te_RegStepTestSuite TestStepNotExist
END_TESTCASE DT-TEF-TestStep-0034
