//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

START_TESTCASE DT-TEF-TestStep-0037
//! @SYMTestCaseID          DT-TEF-TestStep-0037
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        this test test server leaves. the leave number is in the system defined errors, from 0 to -49 with server -SharedData.
//! @SYMTestExpectedResults check the log infomation from 0 to 50. Notice:  one test result is abort.
	PRINT THIS TEST CASE SHOULD BE FAILED! 
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave1
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave2
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave3
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave4
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave5
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave6
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave7
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave8
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave9
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave10
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave11
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave12
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave13
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave14
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave15
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave16
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave17
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave18
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave19
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave20
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave21
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave22
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave23
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave24
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave25
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave26
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave27
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave28
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave29
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave30
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave31
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave32
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave33
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave34
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave35
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave36
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave37
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave38
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave39
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave40
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave41
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave42
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave43
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave44
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave45
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave46
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave47
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave48
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave49
	RUN_TEST_STEP  3  te_RegStepTestSuite LeaveForever ${SYSDRIVE}\testdata\configs\leavenumber.ini 	leave50
END_TESTCASE DT-TEF-TestStep-0037
