//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

START_TESTCASE DT-TEF-TestStep-0011
//! @SYMTestCaseID          DT-TEF-TestStep-0011
//! @SYMCreationDate        28-07-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test abort test step function.
//! @SYMTestExpectedResults Test step result should be unexecuted as the step timeout.
//! @SYMTestActions         1. Delay 100000000 in test step
//!                         2. Set delay 1 in script file.
//!                         3. Check the test result.
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          2. Functional
	PRINT This test case will abort.
	RUN_TEST_STEP 1 te_RegStepTestSuite AbortTestStep
END_TESTCASE DT-TEF-TestStep-0011
