//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

START_TESTCASE DT-TEF-TestStep-0009
//! @SYMTestCaseID          DT-TEF-TestStep-0009
//! @SYMCreationDate        28-07-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Step macros test. TEST, TESTE, TESTL, etc
//! @SYMTestExpectedResults All these test macros should bahave as expected.
//!                         The test result should be pass.
//! @SYMTestActions         1. Call these macros with the correct parameters.
//!                         2. Check the macros' execution result.
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          2. Functional
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTestTrue
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTestFalse
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec0
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec1
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec2
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec3
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec4
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec5
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec6
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTest1Sec7
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTestCheckSec0
	RUN_TEST_STEP 100 te_RegStepTestSuite MacrosTestStep ${SYSDRIVE}\testdata\configs\stepmacros.ini StepMacrosTestCheckSec1
END_TESTCASE DT-TEF-TestStep-0009
