//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite -SharedData

START_TESTCASE DT-TEF-TestStep-0030
//! @SYMTestCaseID          DT-TEF-TestStep-0030
//! @SYMCreationDate        09-12-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test some small functions in CTestStep with server -SharedData.
//! @SYMTestExpectedResults These functions should function well.
//!                         The test result should be pass.
//! @SYMTestActions         Call these functions in test and check the execution result.
	RUN_TEST_STEP 100 te_RegStepTestSuite ShortFunsTestStep ${SYSDRIVE}\testdata\configs\stepshortfuns.ini StepShortFunsSec1
END_TESTCASE DT-TEF-TestStep-0030
