//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	te_RegStepTestSuite

START_TESTCASE DT-TEF-TestStep-0007
//! @SYMTestCaseID          DT-TEF-TestStep-0007
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test function WriteStringToConfig of class CTestStep
//! @SYMTestExpectedResults A string should be write into config file.
//!                         The test result should be pass.
//! @SYMTestActions         Write a string into the configuration file and check the write result.
//! @SYMPREQ                PREQ2261
//! @SYMREQ                 REQ10438
//!                         REQ10440
//! @SYMTestStatus          1. Under Development
	RUN_TEST_STEP 100 te_RegStepTestSuite WriteStringStep ${SYSDRIVE}\testdata\configs\WriteToConfig.ini Section0
END_TESTCASE DT-TEF-TestStep-0007
