//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run test case(s) for suite te_RegStepTestSuite

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\dt-tef-teststep-*.script ${SYSDRIVE}\testdata\scripts\dt-tef-teststep-*.script

CopyFile z:\testdata\configs\error_codes.ini ${SYSDRIVE}\testdata\configs\error_codes.ini
CopyFile z:\testdata\configs\readwriteconfig.ini ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
CopyFile z:\testdata\configs\writetoconfig.ini ${SYSDRIVE}\testdata\configs\writetoconfig.ini
CopyFile z:\testdata\configs\OOMTest.ini ${SYSDRIVE}\testdata\configs\OOMTest.ini
CopyFile z:\testdata\configs\stepmacros.ini ${SYSDRIVE}\testdata\configs\stepmacros.ini
CopyFile z:\testdata\configs\stepshortfuns.ini ${SYSDRIVE}\testdata\configs\stepshortfuns.ini
CopyFile z:\testdata\configs\PanicTest.ini ${SYSDRIVE}\testdata\configs\PanicTest.ini

MakeReadWrite ${SYSDRIVE}\testdata\configs\writetoconfig.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\error_codes.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\readwriteconfig.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\stepmacros.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\OOMTest.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\stepshortfuns.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\PanicTest.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\leavenumber.ini
REMOVE_PREFIX

PREFIX RUN_PROGRAM 50 testexecute
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0005.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0006.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0007.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0008.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0009.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0010.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0011.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0012.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0013.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0014.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0015.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0016.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0017.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0018.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0021.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0022.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0023.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0024.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0025.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0026.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0027.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0028.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0029.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0030.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0031.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0032.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0033.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0034.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0035.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0036.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0037.script
${SYSDRIVE}\testdata\scripts\dt-tef-teststep-0038.script
REMOVE_PREFIX

PRINT Complete te_RegStepTest Suite Tests
