//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Clean the test environment...

PREFIX RUN_UTILS
CopyFile ${SYSDRIVE}\system\data\testexecute.ini ${SYSDRIVE}\system\data\testexecute_test.ini
CopyFile ${SYSDRIVE}\system\data\testexecute.ini.bak ${SYSDRIVE}\system\data\testexecute.ini
DeleteFile ${SYSDRIVE}\system\data\testexecute.ini.bak
REMOVE_PREFIX

PRINT Environment clean complete.
