//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

xPRINT Run all te_XML_FTmgr Suite Tests

LOAD_SUITE te_XML_FTmgrSuite

START_TESTCASE BASESRVCS-XML-CT-4927 // Variation support test case for PREQ 2051 based on feature manager
//!@SYMTestCaseID                BASESRVCS-XML-CT-4925
//!@SYMTestCaseDesc              Checking of inclusion and exclusion of XML components in the built ROM image
//!@SYMTestPriority              Normal
//!@SYMTestActions               Test whether a feature is supported or not
//!@SYMTestExpectedResults       The presence or absence of XML components needs to be found out
//!@SYMDEF                       Not a defect fix. Part of PREQ 2051
RUN_TEST_STEP 100 te_XML_FTmgrSuite XML_flagsStep c:\testdata\configs\te_XML_FTmgrsuite.ini XML_Flags_Test
END_TESTCASE BASESRVCS-XML-CT-4927 // Variation support test case for PREQ 2051 based on feature manager

PRINT Complate_te_XML_FTmgr_Tests
