// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Loading Suite texml2
LOAD_SUITE texml2
DELAY 500

//
//! @SYMTestCaseID	BASESRVCS-XML-CT-4929
//! @SYMTestCaseDesc	Tests the APIs under different memory conditions
//! @SYMPREQ		PREQ2051
//! @SYMTestPriority	High
//! @SYMTestActions	The following APIs are testing under various
//!			memory conditions:
//!			XmlEngOOMTestL
//! @SYMTestExpectedResults	EPass
//

START_TESTCASE BASESRVCS-XML-CT-4929
	RUN_TEST_STEP 100 texml2 XmlEngLeaveOOMStep1
	RUN_TEST_STEP 100 texml2 XmlEngLeaveOOMStep2
END_TESTCASE BASESRVCS-XML-CT-4929

//
//! @SYMTestCaseID	BASESRVCS-XML-CT-4930
//! @SYMTestCaseDesc	Tests the APIs under different memory conditions
//! @SYMPREQ		PREQ2051
//! @SYMTestPriority	High
//! @SYMTestActions	The following APIs are testing under various
//!			memory conditions:
//!			XmlEngXmlCharFromDesL
//!			XmlEngXmlCharFromDes8L 
//!			XmlEngEscapeForXmlValueL 
//! @SYMTestExpectedResults	EPass
//

START_TESTCASE BASESRVCS-XML-CT-4930
	RUN_TEST_STEP 100 texml2 XmlEngEscapeForXmlValueStep1
	RUN_TEST_STEP 100 texml2 XmlEngEscapeForXmlValueStep2
	RUN_TEST_STEP 100 texml2 XmlEngXmlCharFromDes
END_TESTCASE BASESRVCS-XML-CT-4930

//
//! @SYMTestCaseID	BASESRVCS-XML-CT-4931
//! @SYMTestCaseDesc	Tests the APIs in xmlengineutils
//! @SYMPREQ		PREQ2051
//! @SYMTestPriority	High
//! @SYMTestActions	The following APIs are testing under various
//!			memory conditions:
//!			XmlEnginePushL
//!			XmlEnginePopAndClose
//! @SYMTestExpectedResults	EPass
//

START_TESTCASE BASESRVCS-XML-CT-4931
	RUN_TEST_STEP 100 texml2 XmlEnginePushAndPop
END_TESTCASE BASESRVCS-XML-CT-4931

//
//! @SYMTestCaseID	BASESRVCS-XML-CT-49232
//! @SYMTestCaseDesc	Tests the APIs in xmlengineutils
//! @SYMPREQ		PREQ2051
//! @SYMTestPriority	High
//! @SYMTestActions	The following APIs are testing under various
//!			memory conditions:
//!			CopyL
//!			SetL
//!			Free
//!			PushL
//!			Set
//!			AppendL
//!			Size
//!			Copy
//!			AllocAndFreeL
//!			Alloc
//!			AllocLC
//! @SYMTestExpectedResults	EPass
//

START_TESTCASE BASESRVCS-XML-CT-4932
	RUN_TEST_STEP 100 texml2 XmlStringCopy
	RUN_TEST_STEP 100 texml2 XmlStringSetStep1
	RUN_TEST_STEP 100 texml2 XmlStringSetStep2
	RUN_TEST_STEP 100 texml2 XmlStringAppend
	RUN_TEST_STEP 100 texml2 XmlStringAlloc1
	RUN_TEST_STEP 100 texml2 XmlStringAlloc2
	RUN_TEST_STEP 100 texml2 XmlStringAllocAndFree1
	RUN_TEST_STEP 100 texml2 XmlStringAllocAndFree2
	RUN_TEST_STEP 100 texml2 XmlStringCompare
END_TESTCASE BASESRVCS-XML-CT-4932