//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0009
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0009
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Negative Test of "run_program" script command.
//! @SYMTestExpectedResults Test should fail with error code -1.
//! @SYMTestActions         Write "RUN_PROGRAM" to launch a not existed executable file
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckProgram ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0009
	RUN_PROGRAM 5 TIMEWdddd.exe
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckProgram ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0009
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0009
END_TESTCASE DT-TEF-ScriptCommand-0009
