//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-ScriptCommand-0002
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0002
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test "pause" script comman, implement the pause command if JustInTime debugging is switched on.
//! @SYMTestExpectedResults Script execution is paused until key is pressed.
//!                         The test result should be pass.
//! @SYMTestActions         Execute the pause command in script file, check if the execution is paused and after pressing any key, it continue to execute.
	PAUSE	
END_TESTCASE DT-TEF-ScriptCommand-0002
