//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0005
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0005
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test "print" script command.
//! @SYMTestExpectedResults The contents of the PRINT command should be printed to result file.
//!                         The test result should be pass.
//! @SYMTestActions         Write a PRINT command in the test script.
	PRINT THIS TEXT HAS BEEN ADDED TO THE LOG FILE USING THE PRINT COMMAND
	RUN_TEST_STEP 20 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0005
END_TESTCASE DT-TEF-ScriptCommand-0005
