//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0014
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0014
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test "RUN_UTILS" script command.
//! @SYMTestExpectedResults The RUN_UTILS command should run successfully with the specified task.
//!                         Test result should be pass.
//! @SYMTestActions         Execute some tasks with the command RUN_UTILS in script file
	RUN_UTILS MkDir ${SYSDRIVE}\UTILTEST
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckFolderAndFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0014
	
	RUN_UTILS CopyFile ${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0014.script ${SYSDRIVE}\UTILTEST\dt-tef-scriptcommand-0014.script
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckFolderAndFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0014_1
	
	RUN_UTILS DeleteFile ${SYSDRIVE}\UTILTEST\dt-tef-scriptcommand-0014.script
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckFolderAndFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0014_2
	
	RUN_UTILS DeleteDirectory ${SYSDRIVE}\UTILTEST
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckFolderAndFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0014_3
END_TESTCASE DT-TEF-ScriptCommand-0014
