//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0004
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0004
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Negative Test of "prefix" script command.
//! @SYMTestExpectedResults Test should fail with UNEXECUTED status.
//! @SYMTestActions         Write a "PREFIX" statement with no arguments
	PREFIX
	This line should not appear in the log file.
	REMOVE_PREFIX
	RUN_TEST_STEP 20 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0004
END_TESTCASE DT-TEF-ScriptCommand-0004
