//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0015
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0015
//! @SYMCreationDate        23-07-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test if not use print command, the info will not be printed.
//! @SYMTestExpectedResults The information will not be printed in the log file.
//!                         There should be warning message and the test result should be pass.
//! @SYMTestActions         Write something but not use PRINT command.
	THIS TEXT SHOULD NOT HAVE THE WORD INFO IN FRONT OF IT
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0015
END_TESTCASE DT-TEF-ScriptCommand-0015
