//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0007
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0007
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Negative Test of "START_REPEAT" script command.
//! @SYMTestExpectedResults Test should fail with &quot;UNEXECUTED&quot; status.
//! @SYMTestActions         Write START_REPEAT command in script file, but it doesn't have last two required parameters.
	START_REPEAT ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini
	PRINT THIS TEXT SHOULD NOT BE REPEATED 5 TIMES USING THE REPEAT COMMAND
	END_REPEAT
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0007
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0007_1
	RUN_TEST_STEP 10 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0007_2
END_TESTCASE DT-TEF-ScriptCommand-0007

