//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

Load_Server Te_RegScriptCommandServer

START_TESTCASE DT-TEF-ScriptCommand-0006
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0006
//! @SYMCreationDate        26-06-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test "START_REPEAT" script command.
//! @SYMTestExpectedResults PRINT command should be repeated to run for the times defined in the configuration file.
//!                         The test result should be pass.
//! @SYMTestActions         Write "START_REPEATE" command to repeat PRINT command
	START_REPEAT ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0006 repeatParam 
	PRINT THIS TEXT SHOULD BE REPEATED 5 TIMES USING THE REPEAT COMMAND
	END_REPEAT
	RUN_TEST_STEP 20 Te_RegScriptCommandServer CheckLogFile ${SYSDRIVE}\testdata\configs\te_regscriptcommandtest.ini ScriptCommand_0006
END_TESTCASE DT-TEF-ScriptCommand-0006
