//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-ScriptCommand-0016
//! @SYMTestCaseID          DT-TEF-ScriptCommand-0016
//! @SYMCreationDate        17-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        This test TEF CED key word. CED will call ced.exe directly.
//!                         First call run program ceddump to save current configs. Then using ced import dumped config.
//! @SYMTestExpectedResults this test case should pass
  RUN_PROGRAM 5 ceddump.exe -o c:\tefdump.cfg
  CED c:\tefdump.cfg
END_TESTCASE DT-TEF-ScriptCommand-0016
