//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run all te_RegScriptCommandSuite Suite Tests

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\dt-tef-scriptcommand-*.script ${SYSDRIVE}\TestData\scripts\dt-tef-scriptcommand-*.script

CopyFile z:\testdata\configs\repeatparam.ini ${SYSDRIVE}\TestData\configs\repeatparam.ini
CopyFile z:\testdata\configs\shareddatatest.ini ${SYSDRIVE}\TestData\configs\shareddatatest.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\shareddatatest.ini
MakeReadWrite 	${SYSDRIVE}\testdata\configs\repeatparam.ini
REMOVE_PREFIX

PREFIX RUN_SCRIPT
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0005.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0006.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0007.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0008.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0009.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0010.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0011.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0012.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0013.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0014.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0015.script
${SYSDRIVE}\testdata\scripts\dt-tef-scriptcommand-0016.script
REMOVE_PREFIX

PRINT Complete te_RegScriptCommandSuite Suite Tests
