// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run XML xmlengdomnodeset_tef
LOAD_SUITE xmlengdomnodeset_tef
DELAY 500
START_TESTCASE BASESRVCS-XML-CT-4934
//
//! @SYMTestCaseID BASESRVCS-XML-CT-4934
//! @SYMTestCaseDesc Tests the APIs to improve the code coverage
//! @SYMPREQ PREQ2051
//! @SYMTestPriority High
//! @SYMTestActions TThe following API is tested for code coverage
//! RXmlEngXPathExpression::CreateExpressionL RXmlEngXPathExpression::ExtendedContext 
//! RXmlEngXPathExpression::SetExtendedContext RXmlEngNodeSet::Contains
//!	CXmlEngXFormsInstanceMap::NewL LibxmlNodeCleanup
//! @SYMTestExpectedResults EPass
	RUN_TEST_STEP 100 xmlengdomnodeset_tef XmlEngNodeTestSetContains
	RUN_TEST_STEP 100 xmlengdomnodeset_tef XmlEngCreateXFormInstanceMap
	RUN_TEST_STEP 100 xmlengdomnodeset_tef XmlEngXPathCreationTest
	RUN_TEST_STEP 100 xmlengdomnodeset_tef XmlEngLibXMLNodeCleanup
END_TESTCASE BASESRVCS-XML-CT-4934