// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run XML xmlengdom_tef
LOAD_SUITE xmlengdom_tef
DELAY 500
START_TESTCASE BASESRVCS-XML-CT-4933
//
//! @SYMTestCaseID BASESRVCS-XML-CT-4933
//! @SYMTestCaseDesc Tests the APIs to improve the code coverage
//! @SYMPREQ PREQ2051
//! @SYMTestPriority High
//! @SYMTestActions The following API is tested for code coverage
//!					RXmlEngDOMImplementation::Close(TBool)
//! @SYMTestExpectedResults EPass
	RUN_TEST_STEP 100 xmlengdom_tef XmlEngLeaveOOMStep1
END_TESTCASE BASESRVCS-XML-CT-4933