//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-TestClient-0006
//! @SYMTestCaseID          DT-TEF-TestClient-0006
//! @SYMCreationDate        28-10-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        loadding a very long server name. the server name not exist at all, because OS not allowed such long file name. the name length  256 , so the testexecute will report toobig.
//!                         this test case test how testexecute deal with long server name.
//! @SYMTestExpectedResults Because LOAD_SUITE not take as a test step, so this test case should pass.
//!                         this test case will trigger tef check the server name length codes then log the error info.
//!                         this line should appeard in the log file &quot;One or more arguments for the command exceeded allowed limit for length. Skipping test..&quot;
	LOAD_SUITE NotExistAndLongServerNameSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthorSYMScriptAuthor
END_TESTCASE DT-TEF-TestClient-0006
