//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-TestClient-0008
//! @SYMTestCaseID          DT-TEF-TestClient-0008
//! @SYMCreationDate        28-10-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        loading server twice. one is LOAD_SUITE another is LOAD_SERVER.
//!                         this 2 keyword exactly did the samething, TEF take LOAD_SUITE as alias of LOAD_SERVER.
//! @SYMTestExpectedResults this test case will always pass, because loading server command not takes as a test.
//!                         the 2 command exactly do the same thing.
//!                         No error message logged in the log file.
	
LOAD_SUITE	TEF_ClientTestUnit
LOAD_SERVER	TEF_ClientTestUnit	
END_TESTCASE DT-TEF-TestClient-0008
