//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-TestClient-0007
//! @SYMTestCaseID          DT-TEF-TestClient-0007
//! @SYMCreationDate        28-10-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        Low
//! @SYMTestCaseDesc        loading server twice. one is upper case another is lower case.
//!                         the second should not do any thing.
//! @SYMTestExpectedResults this test case should pass.
//!                         the upper and lower case should both OK. the OS not distingish letter case.
//!                         should not any error messag loged in the log file.
LOAD_SUITE	TEF_ClientTestUnit
LOAD_SUITE	tef_clienttestunit
END_TESTCASE DT-TEF-TestClient-0007
