//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_ClientTestUnit

START_TESTCASE DT-TEF-TestClient-0001
//! @SYMTestCaseID          DT-TEF-TestClient-0001
//! @SYMCreationDate        26-08-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This test case will connecting a long test server name, the server name does not exist. TEF will return neme to long KErrTooBig.
//! @SYMTestExpectedResults Connect() return KErrTooBig ==-40 and step is pass.
RUN_TEST_STEP 100 TEF_ClientTestUnit TEFUnit.CTEFClientSuiteUT.TestLongServerName
END_TESTCASE DT-TEF-TestClient-0001
