//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-TestClient-0009
//! @SYMTestCaseID          DT-TEF-TestClient-0009
//! @SYMCreationDate        28-10-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        Low
//! @SYMTestCaseDesc        this test test loading server with directory path.
//!                         z:sysbinte_RegressionSuite
//!                         OS search path will start form {diver letter}sysbin, under other path executable file should not executed by OS.
//!                         So server name no need to specifiy directory name.
//! @SYMTestExpectedResults pass, because loading server command not takes as a test.
//!                         Before &quot;load_suite z:sysbinte_RegressionSuite&quot; will be an ERROR message. Error message is &quot;Failed to Create Server Err = -28&quot;
	LOAD_SERVER z:\sys\bin\TEF_ClientTestUnit
END_TESTCASE DT-TEF-TestClient-0009
