//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_ClientTestUnit

START_TESTCASE DT-TEF-TestClient-0003
//! @SYMTestCaseID          DT-TEF-TestClient-0003
//! @SYMCreationDate        26-08-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This test case is normal test step.
//! @SYMTestExpectedResults test should Pass.
RUN_TEST_STEP 100 TEF_ClientTestUnit TEFUnit.CTEFClientSuiteUT.TestRunTestStepL
END_TESTCASE DT-TEF-TestClient-0003
