//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_ClientTestUnit

START_TESTCASE DT-TEF-TestClient-0002
//! @SYMTestCaseID          DT-TEF-TestClient-0002
//! @SYMCreationDate        26-08-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This test case run a long step name,call RunTestStep() directly with a very long test step name.
//! @SYMTestExpectedResults the step name not exists so this case won't cause any trouble. The test case should pass.
RUN_TEST_STEP 100 TEF_ClientTestUnit TEFUnit.CTEFClientSuiteUT.TestOpenLongStepNameL
END_TESTCASE DT-TEF-TestClient-0002
