//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run test case(s) for suite tef_clienttestunit
PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\dt-tef-testclient-*.script		 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-*.script

CopyFile z:\testdata\configs\te_tefclienttest.ini		 ${SYSDRIVE}\testdata\configs\te_tefclienttest.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\te_tefclienttest.ini
REMOVE_PREFIX

RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0001.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0002.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0003.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0004.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0005.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0006.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0007.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0008.script
RUN_SCRIPT 	 ${SYSDRIVE}\testdata\scripts\dt-tef-testclient-0009.script

