//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	Te_RegConcurrentTestSuite1
LOAD_SUITE	Te_RegConcurrentTestSuite2
LOAD_SUITE	Te_RegConcurrentTestSuite3 -SharedData
PRINT

START_REPEAT ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini Repeat Repeat
CONCURRENT
START_TESTCASE DT-TEF-Concurrent-0012
//! @SYMTestCaseID          DT-TEF-Concurrent-0012
//! @SYMCreationDate        03-09-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test Concurrent functionalities of TEF steps with 3 servers two of them not shared data and the other one shared data. (in loop cycle)
//! @SYMTestExpectedResults Test cases should all passed with the expected behavior.
//!                         The steps inside concurrent block should be executed simultaneously while others are not.
//!                         But in concurrent block, if a shared data server step executes, the execution of next step will wait there until this step finished.
//!                         the steps in the loop cycle will be executed for the times which the loop specifies.
//! @SYMTestActions         1. Load 3 servers servers two of them not shared data and the other one shared data.
//!                         2. Call START_REPEAT.
//!                         3. Call CONCURRENT.
//!                         4. Run some steps in a test case (both shared data and non-shared data servers).
//!                         5. Call CONSECUTIVE.
//!                         4. Call END-REPEAT.
//!                         5. Run some more steps in another test case (steps of both non-shared data servers and shared data server).
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite3 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite3 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep1
END_TESTCASE DT-TEF-Concurrent-0012
CONSECUTIVE
END_REPEAT
START_TESTCASE DT-TEF-Concurrent-0012-1
//! @SYMTestCaseID          DT-TEF-Concurrent-0012
//! @SYMCreationDate        03-09-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test Concurrent functionalities of TEF steps with 3 servers two of them not shared data and the other one shared data. (in loop cycle)
//! @SYMTestExpectedResults Test cases should all passed with the expected behavior.
//!                         The steps inside concurrent block should be executed simultaneously while others are not.
//!                         But in concurrent block, if a shared data server step executes, the execution of next step will wait there until this step finished.
//!                         the steps in the loop cycle will be executed for the times which the loop specifies.
//! @SYMTestActions         1. Load 3 servers servers two of them not shared data and the other one shared data.
//!                         2. Call START_REPEAT.
//!                         3. Call CONCURRENT.
//!                         4. Run some steps in a test case (both shared data and non-shared data servers).
//!                         5. Call CONSECUTIVE.
//!                         4. Call END-REPEAT.
//!                         5. Run some more steps in another test case (steps of both non-shared data servers and shared data server).
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite3 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite3 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep2
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep2
	
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegCheckTestResultStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini 60
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegCheckTestResultStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini 0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite3 Te_RegCheckTestResultStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini 60
END_TESTCASE DT-TEF-Concurrent-0012-1
