//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	Te_RegConcurrentTestSuite1
LOAD_SUITE	Te_RegConcurrentTestSuite2
PRINT

START_TESTCASE DT-TEF-Concurrent-0006
//! @SYMTestCaseID          DT-TEF-Concurrent-0006
//! @SYMCreationDate        03-09-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test Concurrent functionalities of TEF steps with two servers not shared data.
//! @SYMTestExpectedResults Test cases should all passed with the expected behavior.
//!                         The steps in the test case which inside concurrent block
//!                         should be executed simultaneously while others are not.
//! @SYMTestActions         1. Load two server without shared data.
//!                         2. Run some steps in a test case (of two servers).
//!                         3. Call CONCURRENT
//!                         4. Run some more steps in another test case (of two servers).
//!                         5. Call CONSECUTIVE
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep0
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep0
END_TESTCASE DT-TEF-Concurrent-0006
CONCURRENT
START_TESTCASE DT-TEF-Concurrent-0006-1
//! @SYMTestCaseID          DT-TEF-Concurrent-0006-1
//! @SYMCreationDate        03-09-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test Concurrent functionalities of TEF steps with two servers not shared data.
//! @SYMTestExpectedResults Test cases should all passed with the expected behavior.
//!                         The steps in the test case which inside concurrent block
//!                         should be executed simultaneously while others are not.
//! @SYMTestActions         1. Load two server without shared data.
//!                         2. Run some steps in a test case (of two servers).
//!                         3. Call CONCURRENT
//!                         4. Run some more steps in another test case (of two servers).
//!                         5. Call CONSECUTIVE
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegWaitStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini WaitStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegLoopStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini LoopStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegAccessStaticVarStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini AccessStaticVarStep1
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegDummyStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini DummyStep1
END_TESTCASE DT-TEF-Concurrent-0006-1
CONSECUTIVE
START_TESTCASE DT-TEF-Concurrent-0006-2
//! @SYMTestCaseID          DT-TEF-Concurrent-0006-2
//! @SYMCreationDate        03-09-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test Concurrent functionalities of TEF steps with two servers not shared data.
//! @SYMTestExpectedResults Test cases should all passed with the expected behavior.
//!                         The steps in the test case which inside concurrent block
//!                         should be executed simultaneously while others are not.
//! @SYMTestActions         1. Load two server without shared data.
//!                         2. Run some steps in a test case (of two servers).
//!                         3. Call CONCURRENT
//!                         4. Run some more steps in another test case (of two servers).
//!                         5. Call CONSECUTIVE
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite1 Te_RegCheckTestResultStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini 20
	RUN_TEST_STEP 100 Te_RegConcurrentTestSuite2 Te_RegCheckTestResultStep ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini 20
END_TESTCASE DT-TEF-Concurrent-0006-2
