//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run test case(s) for suite te_regconcurrenttestsuite

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\
CopyFile z:\testdata\scripts\dt-tef-concurrent-*.script ${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-*.script
CopyFile z:\testdata\configs\te_regconcurrenttestsuite.ini ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\te_regconcurrenttestsuite.ini
REMOVE_PREFIX

PREFIX RUN_SCRIPT
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0005.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0006.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0007.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0008.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0009.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0010.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0011.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0012.script
${SYSDRIVE}\testdata\scripts\dt-tef-concurrent-0013.script
REMOVE_PREFIX
