# wml1_1codepage255attributetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Wml1_1CodePage255AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Attribute names
!// CodePage 255
ETestAttr 					TestAttribute
# //////////////////////////////////////////////////////////////////////
!// For XML
EUri						-//WAPFORUM//DTD WML 1.1 ATTRIBUTE SWITCH TEST//EN
!// For WBXML
EPublicId					04~FF
EFormalPublicId				-//WAPFORUM//DTD WML 1.1//EN~FF