# wml1_1codepage255attributevaluetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Wml1_1CodePage255AttributeValueTable
# //////////////////////////////////////////////////////////////////////
!// Attribute value names
!// CodePage 255
ETestAttr
