//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER TEF_LoggerTestBlock -SharedData

START_TESTCASE DT-TEF-Logger-0034
//! @SYMTestCaseID          DT-TEF-Logger-0034
//! @SYMCreationDate        09-07-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        Run test with a very long section name and a long key. Makes sure test will support long string arguments
//!                         The contest loaded from ini will be wite to log file.
//!                         This command will panic 11 at TVerdict CTestExecuteLogger::LogHTMLBlock( const TTEFItemArray&amp; aItemArray )
//!                         When append "blockLine += KTEFFontEnd;" should be triple TBuf&lt;KMaxTestExecuteCommandLength&gt; blockLine;
//!                         
//!                         HTML, XML log test
//! @SYMTestExpectedResults This two command should pass with no error. the maximum length is 255

	START_TEST_BLOCK 100	TEF_LoggerTestBlock  ${SYSDRIVE}\TestData\configs\loggerTest.ini
	CREATE_OBJECT	TEFLoggerTestWrapper	TLogSeverity	
COMMAND TLogSeverity GetLongSectionName ALooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongSection
COMMAND TLogSeverity GetLongKeyName ALongKeySection                                                                                                           
	END_TEST_BLOCK
END_TESTCASE DT-TEF-Logger-0034
