//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite
PRINT Reuse te_RegBlockTestSuite Server

START_TESTCASE DT-TEF-Logger-0022
//! @SYMTestCaseID          DT-TEF-Logger-0022
//! @SYMCreationDate        09-07-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        Test Panic result compare.
//!                         Block test compare PanicCode and PanicString. Panic String with a space.
//!                         Compare expacted test result and the real result.
//!                         reuse te_RegBlockTestSuite.
//!                         
//!                         XML log test
//! @SYMTestExpectedResults the expacted panic string has two words, and this should be same with test result.
//!                         COMMAND is paniced so the command result is INCONCLUSIVE.
//!                         This case should pass.

	START_TEST_BLOCK	100	te_RegBlockTestSuite  ${SYSDRIVE}\TestData\configs\loggerTest.ini
		CREATE_OBJECT	te_RegBlockTestWrapper				LoggerTESTCase02_obj
		COMMAND			LoggerTESTCase02_obj PanickingFunction	LoggerTESTCase02_obj_Panic
	END_TEST_BLOCK	!PanicString="FSCLIENT panic"	!PanicCode=24 
END_TESTCASE DT-TEF-Logger-0022

