//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER TEF_LoggerTestBlock -SharedData

START_TESTCASE DT-TEF-Logger-0001
//! @SYMTestCaseID          DT-TEF-Logger-0001
//! @SYMCreationDate        09-07-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        Critical
//! @SYMTestCaseDesc        Print all emun Levels of the log out put.
//!                         The following levels will be covered.
//!                         {ESevrErr  = 1,ESevrHigh, ESevrWarn,ESevrMedium, ESevrInfo, ESevrLow, ESevrAll};
//!                         
//!                         the perl script will compare the test result with expected result. The test result comes form the run time result and the expected result comes form scripts.
//!                         When test case/step finished, the perl script will compare test result and expected result, at last print out test case/step pass or fail information.
//!                         The compare function codes are writing the perl script, seperate for this poject. It will placed under \RegressionTest\baseline\logcomparetool
//!                         
//!                         HTML log test        
//! @SYMTestExpectedResults all the infomation will be logged with provided level number.
//!                         Pass
//! @SYMTestActions         1. create TEFLoggerWrapper
//!                         2. test all kinds of error level.

	START_TEST_BLOCK 100	TEF_LoggerTestBlock ${SYSDRIVE}\TestData\configs\loggerTest.ini
		CREATE_OBJECT	TEFLoggerTestWrapper	TLogSeverity
		COMMAND		TLogSeverity			Print				ESevrErr
		COMMAND		TLogSeverity			Print				ESevrHigh
		COMMAND		TLogSeverity			Print				ESevrWarn
		COMMAND		TLogSeverity			Print				ESevrMedium
		COMMAND		TLogSeverity			Print				ESevrInfo
		COMMAND		TLogSeverity			Print				ESevrLow
		COMMAND		TLogSeverity			Print				ESevrAll
	END_TEST_BLOCK
END_TESTCASE DT-TEF-Logger-0001

