//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER TEF_LoggerTestBlock -SharedData

START_TESTCASE DT-TEF-Logger-0044
//! @SYMTestCaseID          DT-TEF-Logger-0044
//! @SYMCreationDate        14-07-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        Print the not exsits levels of the log out put.
//!                         The level EAobveSevrAll equre to ESevrAll+1
//!                         The EAobveSevrAll is 56635 a very large number.
//!                         
//!                         HTML, XML log test
//! @SYMTestExpectedResults The log infomation are porperly output and the level number should out put as well.
//!                         command should pass, and test case should pass as well.

	START_TEST_BLOCK 100	TEF_LoggerTestBlock ${SYSDRIVE}\TestData\configs\loggerTest.ini
		CREATE_OBJECT	TEFLoggerTestWrapper	TLogSeverity
		COMMAND		TLogSeverity			Print				EAobveSevrAll
		COMMAND		TLogSeverity			Print				ESupperLarge
	END_TEST_BLOCK	
END_TESTCASE DT-TEF-Logger-0044
