//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite
PRINT Reuse te_RegBlockTestSuite Server

START_TESTCASE DT-TEF-Logger-0036
//! @SYMTestCaseID          DT-TEF-Logger-0036
//! @SYMCreationDate        09-07-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        Test Panic result compare.
//!                         Block test comparePanicString and  PanicCode.
//!                         Compare expacted test result and the real result.
//!                         reuse te_RegBlockTestSuite.
//!                         
//!                         HTML, XML log test
//! @SYMTestExpectedResults In this test case should pass.
//!                         The expected result and the test result should be same.

	START_TEST_BLOCK 100	te_RegBlockTestSuite  ${SYSDRIVE}\TestData\configs\loggerTest.ini
		CREATE_OBJECT	te_RegBlockTestWrapper		LoggerTESTCase01_obj
		COMMAND			LoggerTESTCase01_obj PanickingFunction	LoggerTESTCase01_obj_Panic
	END_TEST_BLOCK	!PanicString=FSCLIENT	!PanicCode=24 
END_TESTCASE DT-TEF-Logger-0036
