//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
PREFIX RUN_UTILS
CopyFile ${SYSDRIVE}\system\data\testexecute.ini  ${SYSDRIVE}\backupTEFc.ini

MkDir ${SYSDRIVE}\system\
MkDir ${SYSDRIVE}\system\data\
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
//hardware
CopyFile z:\testdata\configs\xml.ini  ${SYSDRIVE}\system\data\xml.ini
CopyFile z:\testdata\configs\html.ini ${SYSDRIVE}\system\data\html.ini
CopyFile z:\testdata\configs\BOTH.ini ${SYSDRIVE}\system\data\BOTH.ini
//emulator
CopyFile c:\testdata\configs\xml.ini  ${SYSDRIVE}\system\data\xml.ini
CopyFile c:\testdata\configs\html.ini ${SYSDRIVE}\system\data\html.ini
CopyFile c:\testdata\configs\BOTH.ini ${SYSDRIVE}\system\data\BOTH.ini


CopyFile z:\testdata\scripts\dt-tef-logger-0001.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0001.script
CopyFile z:\testdata\scripts\dt-tef-logger-0002.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0002.script
CopyFile z:\testdata\scripts\dt-tef-logger-0003.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0003.script
CopyFile z:\testdata\scripts\dt-tef-logger-0004.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0004.script
CopyFile z:\testdata\scripts\dt-tef-logger-0005.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0005.script
CopyFile z:\testdata\scripts\dt-tef-logger-0006.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0006.script
CopyFile z:\testdata\scripts\dt-tef-logger-0007.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0007.script
CopyFile z:\testdata\scripts\dt-tef-logger-0008.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0008.script
CopyFile z:\testdata\scripts\dt-tef-logger-0009.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0009.script
CopyFile z:\testdata\scripts\dt-tef-logger-0010.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0010.script
CopyFile z:\testdata\scripts\dt-tef-logger-0011.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0011.script
CopyFile z:\testdata\scripts\dt-tef-logger-0012.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0012.script
CopyFile z:\testdata\scripts\dt-tef-logger-0013.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0013.script
CopyFile z:\testdata\scripts\dt-tef-logger-0014.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0014.script
CopyFile z:\testdata\scripts\dt-tef-logger-0015.script	${SYSDRIVE}\testdata\scripts\dt-tef-logger-0015.script
CopyFile z:\testdata\scripts\logger_postest.script	${SYSDRIVE}\testdata\scripts\logger_postest.script    
CopyFile z:\testdata\scripts\logger_pretest.script	${SYSDRIVE}\testdata\scripts\logger_pretest.script    
CopyFile z:\testdata\scripts\post_log_both.script	${SYSDRIVE}\testdata\scripts\post_log_both.script     
CopyFile z:\testdata\scripts\post_log_html.script	${SYSDRIVE}\testdata\scripts\post_log_html.script     
CopyFile z:\testdata\scripts\post_log_xml.script	${SYSDRIVE}\testdata\scripts\post_log_xml.script      
CopyFile z:\testdata\scripts\pre_log_both.script	${SYSDRIVE}\testdata\scripts\pre_log_both.script      
CopyFile z:\testdata\scripts\pre_log_html.script	${SYSDRIVE}\testdata\scripts\pre_log_html.script      
CopyFile z:\testdata\scripts\pre_log_xml.script	${SYSDRIVE}\testdata\scripts\pre_log_xml.script
CopyFile z:\testdata\scripts\te_reglogger_html.script	${SYSDRIVE}\testdata\scripts\te_reglogger_html.script
CopyFile z:\testdata\scripts\te_reglogger_xml.script	${SYSDRIVE}\testdata\scripts\te_reglogger_xml.script
CopyFile z:\testdata\scripts\te_reglogger_both.script	${SYSDRIVE}\testdata\scripts\te_reglogger_both.script     

MakeReadWrite ${SYSDRIVE}\system\data\xml.ini      
MakeReadWrite ${SYSDRIVE}\system\data\html.ini     
MakeReadWrite ${SYSDRIVE}\system\data\BOTH.ini

REMOVE_PREFIX
