//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PREFIX RUN_UTILS
CopyFile ${SYSDRIVE}\backupTEFc.ini  ${SYSDRIVE}\system\data\testexecute.ini
DeleteFile ${SYSDRIVE}\backupTEFc.ini 
DeleteFile ${SYSDRIVE}\system\data\xml.ini 
DeleteFile ${SYSDRIVE}\system\data\html.ini
DeleteFile ${SYSDRIVE}\system\data\BOTH.ini
REMOVE_PREFIX
