//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\dt-tef-logger-*.script ${SYSDRIVE}\testdata\scripts\dt-tef-logger-*.script

CopyFile z:\testdata\configs\loggertest.ini ${SYSDRIVE}\testdata\configs\loggertest.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\loggertest.ini
REMOVE_PREFIX

PREFIX RUN_PROGRAM 50 testexecute
${SYSDRIVE}\testdata\scripts\logger_pretest.script

${SYSDRIVE}\testdata\scripts\pre_log_html.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0005.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0006.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0007.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0008.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0009.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0010.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0011.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0012.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0013.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0014.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0015.script
${SYSDRIVE}\testdata\scripts\post_log_html.script

${SYSDRIVE}\testdata\scripts\pre_log_xml.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0016.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0017.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0018.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0019.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0020.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0021.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0022.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0023.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0024.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0025.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0026.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0027.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0028.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0029.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0030.script
${SYSDRIVE}\testdata\scripts\post_log_xml.script

${SYSDRIVE}\testdata\scripts\pre_log_both.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0031.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0032.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0033.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0034.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0035.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0036.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0037.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0038.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0039.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0040.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0041.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0042.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0043.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0044.script
${SYSDRIVE}\testdata\scripts\dt-tef-logger-0045.script
${SYSDRIVE}\testdata\scripts\post_log_both.script

${SYSDRIVE}\testdata\scripts\logger_posttest.script
REMOVE_PREFIX
