//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0016.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0017.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0018.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0019.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0020.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0021.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0022.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0023.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0024.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0025.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0026.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0027.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0028.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0029.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0030.script
