//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0031.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0032.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0033.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0034.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0035.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0036.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0037.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0038.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0039.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0040.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0041.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0042.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0043.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0044.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0045.script
