//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0001.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0002.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0003.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0004.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0005.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0006.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0007.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0008.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0009.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0010.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0011.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0012.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0013.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0014.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-logger-0015.script
