# XML String table
fstringtable XMLEntityReferences
#
# Standard XML Entity References
# These are assumed to have a maximum length of 20 in the generic
# entity converter.  If any built in entity reference is added
# with a length greater than 20 the value of KMaxBuiltinEntityLength
# in GMXMLEntityConverter.cpp will need to be modified.
#
ELT &lt; <
EAmp &amp; &
EGt &gt; >
EDbleQuote &quot; \"
ESingleQuote &apos; '
