//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Legendary RUN_TEST_STEP steps for confirming backward compatibility
//
PRINT Run all Sample Tests 
//
LOAD_SUITE SampleServer
//
#
PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\SampleTest\
CopyFile z:\SampleTest\SampleTest1.script ${SYSDRIVE}\SampleTest\SampleTest1.Script
CopyFile z:\SampleTest\SampleTest.ini ${SYSDRIVE}\SampleTest\SampleTest.ini
MakeReadWrite ${SYSDRIVE}\SampleTest\SampleTest1.Script
MakeReadWrite ${SYSDRIVE}\SampleTest\SampleTest.ini
REMOVE_PREFIX

START_TESTCASE TC012344
START_REPEAT ${SYSDRIVE}\sampletest\sampletest.ini SectionOne repeatParam
RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
END_REPEAT
END_TESTCASE TC012344

START_TESTCASE TC012345
RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
END_TESTCASE TC012345

//RUN_TEST_STEP_RESULT 0 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
//RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
//RUN_PANIC_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne

START_TESTCASE TC012346
RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
DELAY 5000
START_REPEAT ${SYSDRIVE}\sampletest\sampletest.ini SectionOne repeatParam
RUN_SCRIPT ${SYSDRIVE}\sampletest\sampletest1.script
RUN_PROGRAM Eshell.exe
END_REPEAT
RUN_PANIC_STEP_RESULT 1 SampleServer 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\SampleTest.ini SectionTwo
END_TESTCASE TC012346

START_REPEAT ${SYSDRIVE}\sampletest\sampletest.ini SectionOne repeatParam
CONSECUTIVE
PREFIX RUN_PANIC_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini
SectionTwo
SectionTwo
REMOVE_PREFIX
END_REPEAT

PRINT RUN_TEST_STEP with !TEF Parameters

PRINT Test that !Error works as expected when the test step result sets the correct error return value
RUN_TEST_STEP !Error=-43 100 SampleServer SampleStep4  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne

PRINT Test that !Panic works correctly when the test step panics with a matching panic string
RUN_TEST_STEP !PanicString=SampleServer 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo
RUN_TEST_STEP !PanicString="SampleServer" 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo
RUN_TEST_STEP !PanicCode=1 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo

PRINT Test that !Result works as RUN_TEST_STEP_RESULT
RUN_TEST_STEP !Result=Pass 100 SampleServer SampleStep4  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne

PRINT Test that !Heap allocates the correct size heap value for the test step thread
RUN_TEST_STEP !Heap=0x10000 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP !Heap=0x10 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP !Heap=0x1000000 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP !Heap=0x0 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne

PRINT Test various combinations of TEF parameters being passed in
RUN_TEST_STEP !PanicCode=1 !PanicString=SampleServer 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo
RUN_TEST_STEP !Error=-43 !Heap=0x10000 100 SampleServer SampleStep4  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP !PanicString=SampleServer !Heap=0x10000 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo
RUN_TEST_STEP !PanicString=SampleServer !PanicCode=1 !Heap=0x10000 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo

