//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
PRINT Run all Sample Tests 
//
LOAD_SUITE SampleServer -SharedData
//
#
RUN_TEST_STEP 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP 100 SampleServer SampleStep3  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP 100 SampleServer SampleStep2  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
RUN_TEST_STEP 100 SampleServer SampleStep3  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
PAUSE
RUN_PANIC_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionTwo
RUN_TEST_STEP 100 SampleServer SampleStep1  ${SYSDRIVE}\sampletest\sampleTest.ini SectionOne
