//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE AccessServer
LOAD_SUITE GlobalShareServer
SHARED_DATA ${SYSDRIVE}\sampletest\SharedDataTest.ini SectionThree
CONCURRENT
RUN_TEST_STEP 100 AccessServer AccessStep1
RUN_TEST_STEP 100 GlobalShareServer GlobalShareStep1  ${SYSDRIVE}\sampletest\SharedDataTest.ini SectionOne
RUN_TEST_STEP 100 AccessServer AccessStep2
RUN_TEST_STEP 100 GlobalShareServer GlobalShareStep2  ${SYSDRIVE}\sampletest\SharedDataTest.ini SectionOne
CONSECUTIVE
RUN_TEST_STEP 100 AccessServer AccessStep2
RUN_TEST_STEP 100 GlobalShareServer GlobalShareStep2  ${SYSDRIVE}\sampletest\SharedDataTest.ini SectionTwo
RUN_TEST_STEP 100 AccessServer AccessStep1
RUN_TEST_STEP 100 GlobalShareServer GlobalShareStep1  ${SYSDRIVE}\sampletest\SharedDataTest.ini SectionOne