# si1_0stringdict00attributetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Si1_0StringDict00AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EAction1 		action
EAction2 		action
EAction3 		action
EAction4 		action
EAction5 		action
ECreated 		created
EHref1 		href
EHref2 		href
EHref3 		href
EHref4 		href
EHref5 		href
ESiExpires 		si-expires
ESiId 		si-id
EClass 		class