# si1_0stringdict00attributevaluetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Si1_0StringDict00AttributeValueTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EAction1 		signal-none
EAction2 		signal-low
EAction3 		signal-medium
EAction4 		signal-high
EAction5 		delete
ECreated
EHref1
EHref2 		http://
EHref3 		http://www.
EHref4 		https://
EHref5 		https://www.
ESiExpires
ESiId
EClass
ECom 			.com/
EEdu 			.edu/
ENet 			.net/
EOrg 			.org/