# wml1_1codepage00tagtable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Wml1_1CodePage00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EA			a
EAnchor		anchor
EAccess		access
EB			b
EBig			big
EBr			br
ECard			card
EDo			do
EEm			em
EFieldset		fieldset
EGo			go
EHead			head
EI			i
EImg			img
EInput		input
EMeta			meta
ENoop			noop
EP			p
EPostfield		postfield
EPrev			prev
EOnevent		onevent
EOptgroup		optgroup
EOption		option
ERefresh		refresh
ESelect		select
ESetvar		setvar
ESmall		small
EStrong		strong
ETable		table
ETd			td
ETemplate		template
ETimer		timer
ETr			tr
EU			u
EWml			wml
# //////////////////////////////////////////////////////////////////////
!// For XML
EUri						-//WAPFORUM//DTD WML 1.1//EN
!// For WBXML
EPublicId					4~0
EFormalPublicId				-//WAPFORUM//DTD WML 1.1//EN~0
