# wml1_1codepage00attributevaluetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Wml1_1CodePage00AttributeValueTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EAcceptcharset
EAlign1
EAlign2				bottom
EAlign3				center
EAlign4				left
EAlign5				middle
EAlign6				right
EAlign7				top
EAlt
EClass
EColumns
EContent1
EContent2				application/vnd.wap.wmlc;charset=
EDomain
EEmptyok1				false
EEmptyok2				true
EFormat
EForua1				false
EForua2				true
EHeight
EHref1
EHref2				http://
EHref3				https://
EHspace
EHttpequiv1
EHttpequiv2				Content-Type
EHttpequiv3				Expires
EId
EIvalue
EIname
ELabel
ELocalsrc
EMaxlength
EMethod1				get
EMethod2				post
EMode1				nowrap
EMode2				wrap
EMultiple1				false
EMultiple2				true
EName
ENewcontext1			false
ENewcontext2			true
EOnenterbackward
EOnenterforward
EOnpick
EOntimer
EOptional1				false
EOptional2				true
EPath
EScheme
ESendreferer1			false
ESendreferer2			true
ESize
ESrc1
ESrc2					http://
ESrc3					https://
EOrdered1				true
EOrdered2				false
ETabindex
ETitle
EType1
EType2				accept
EType3				delete
EType4				help
EType5				password
EType6				onpick
EType7				onenterbackward
EType8				onenterforward
EType9				ontimer
EType10				options
EType11				prev
EType12				reset
EType13				text
EType14				vnd.
EValue
EVspace
EWidth
EXmllang