# wml1_1codepage00attributetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Wml1_1CodePage00AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EAcceptcharset 			accept-charset
EAlign1				align
EAlign2				align
EAlign3				align
EAlign4				align
EAlign5				align
EAlign6				align
EAlign7				align
EAlt					alt
EClass				class
EColumns				column
EContent1				content
EContent2				content
EDomain				domain
EEmptyok1				emptyok
EEmptyok2				emptyok
EFormat				format
EForua1				forua
EForua2				forua
EHeight				height
EHref1				href
EHref2				href
EHref3				href
EHspace				hspace
EHttpequiv1				http-equiv
EHttpequiv2				http-equiv
EHttpequiv3				http-equiv
EId					id
EIvalue				ivalue
EIname				iname
ELabel				label
ELocalsrc				localsrc
EMaxlength				maxlength
EMethod1				method
EMethod2				method
EMode1				mode
EMode2				mode
EMultiple1				multiple
EMultiple2				multiple
EName					name
ENewcontext1			newcontext
ENewcontext2			newcontext
EOnenterbackward			onenterbackward
EOnenterforward			onenterforward
EOnpick				onpick
EOntimer				ontimer
EOptional1				optional
EOptional2				optional
EPath					path
EScheme				scheme
ESendreferer1			sendreferer
ESendreferer2			sendreferer
ESize					size
ESrc1					src
ESrc2					src
ESrc3					src
EOrdered1				ordered
EOrdered2				ordered
ETabindex				tabindex
ETitle				title
EType1				type
EType2				type
EType3				type
EType4				type
EType5				type
EType6				type
EType7				type
EType8				type
EType9				type
EType10				type
EType11				type
EType12				type
EType13				type
EType14				type
EValue				value
EVspace				vspace
EWidth				width
EXmllang				xml:lang