//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0059
//! @SYMTestCaseID          DT-TEF-TestBlock-0059
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        //! @SYMTestCaseDesc            Test that if !PanicCode and !Result parameters are present then both are taken into account, so if the panic
//!                         //!                                     is not thrown then the test case must fail.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Create a block that expects !PanicCode=1 and !Result=Fail. Set block result to FAIL.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		DELAY		1000000
		COMMAND		DummyObj	SetBlockResult			BlockResult_Fail
	END_TEST_BLOCK		!PanicCode=1	!Result=Fail
END_TESTCASE DT-TEF-TestBlock-0059
