//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0091
//! @SYMTestCaseID          DT-TEF-TestBlock-0091
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test result is set multiple times, check that the last value is taken into account (the block expects to be Fail).
//! @SYMTestExpectedResults Test case result is PASS.
//! @SYMTestActions         Use a test block that expects !Result=Fail and call several commands that set block result to Pass, the last command that sets block result to Fail.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Fail
	END_TEST_BLOCK		!Result=Fail
END_TESTCASE DT-TEF-TestBlock-0091
