//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite -SharedData

START_TESTCASE DT-TEF-TestBlock-0008
//! @SYMTestCaseID          DT-TEF-TestBlock-0008
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Multiple usage of RESTORE_OBJECT (in two different blocks).
//! @SYMTestExpectedResults The test completes without errors.
//!                         The test result should be pass.
//! @SYMTestActions         Create multiple objects, with individual lookup names. Ensure the new
//!                         objects are saved to the store for later use. Use the new command block to
//!                         transfer ownership of one of these objects to the persistent dictionary.
//!                         Relevant persistent object is available across multiple test block executions.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase024_obj
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase024_obja
		STORE		TestCase024_obj
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		RESTORE_OBJECT	te_RegBlockTestWrapper	TestCase024_obj
		COMMAND		TestCase024_obj			DummyFunction
		STORE		TestCase024_obj
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		RESTORE_OBJECT	te_RegBlockTestWrapper	TestCase024_obj
		COMMAND		TestCase024_obj			DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0008
