//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0094
//! @SYMTestCaseID          DT-TEF-TestBlock-0094
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Use OUTSTANDING to let an active object finish it's work.
//! @SYMTestExpectedResults The test case result must be PASS and the active object's work wasn't complete before OUTSTANDING call and it must be complete after the OUTSTANDING.
//! @SYMTestActions         Create a test block, create an active object (RTimer) in the test block and activate it. Call OUTSTANDING
//!                         command for a time sufficient to let the active object to finish it's work. Also check that the
//!                         active object's work is really complete.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase089_obj
		COMMAND		TestCase089_obj			AddActiveObjectToScheduler
		COMMAND		TestCase089_obj			ActivateActiveObject		TestCase089_obj
		COMMAND		TestCase089_obj			CheckActiveObjectWorkIsComplete		TestCase089_must_be_complete_false
		OUTSTANDING
		COMMAND		TestCase089_obj			CheckActiveObjectWorkIsComplete		TestCase089_must_be_complete_true
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0094
