//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0102
//! @SYMTestCaseID          DT-TEF-TestBlock-0102
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        A block with !Result expected to be other than Pass, Fail,
//!                         Inconclusive, TestSuiteError, Abort and Ignore.
//!                         The command executes a function that also sets the value as the block result.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         1. In a block with !Result=999 create a wrapper object
//!                         2. Call a command that calls a function that sets the block result to 999 using CDataWrapper::SetBlockResult()
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper		DummyObj
		COMMAND		DummyObj	SetBlockResult		TestCase105_obj_Result
	END_TEST_BLOCK		!Result=999
END_TESTCASE DT-TEF-TestBlock-0102
