//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0103
//! @SYMTestCaseID          DT-TEF-TestBlock-0103
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Using blank lines inside a test block.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         In a block create a wrapper object and call a command. Use a pair of blank lines to delimit the instructions
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini

		CREATE_OBJECT	te_RegBlockTestWrapper		DummyObj


		COMMAND		DummyObj	DummyFunction



	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0103
