//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0064
//! @SYMTestCaseID          DT-TEF-TestBlock-0064
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that configuration ini file and it's section are accessed without problems.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         1. Use a START_TEST_BLOCK followed by a correct ini-file path.
//!                         2. Use CREATE_OBJECT to create an object providing an existing ini-section name of the ini-file.
//!                         3. Call a command that ensures that the wrapper object can be found in the dictionary (the
//!                         same ini-file section is provided as object reference section and command's parameters section).
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase007_obj
		COMMAND		TestCase007_obj			GetDataWrapper			TestCase007_obj
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0064
