//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0024
//! @SYMTestCaseID          DT-TEF-TestBlock-0024
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Provide a passing command with a non numeric error code.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Call a COMMAND instruction with !Error=Six TEF parameter.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase030_obj
		COMMAND		!Error=Six TestCase030_obj	DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0024
