//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0019
//! @SYMTestCaseID          DT-TEF-TestBlock-0019
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Try to create multiple objects with the same lookup name
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         1. Use CREATE_OBJECT to create an object.
//!                         2. Use CREATE_OBJECT to create an object with the same name as the previous has.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase022_obj
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase022_obj
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0019
