//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0111
//! @SYMTestCaseID          DT-TEF-TestBlock-0111
//! @SYMCreationDate        28-08-2008
//! @SYMAuthor              extjasonzhou
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test test block with null controller nor dictionary.
//! @SYMTestExpectedResults The return value of these functions should be EFail.
//! @SYMTestActions         1. Create a test wrapper
//!                         2. Calls the functions of the test wrapper.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TC0111_obj_name
		COMMAND		TC0111_obj_name		TestNullController TC0111_ValSection
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0111
