//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0071
//! @SYMTestCaseID          DT-TEF-TestBlock-0071
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        A test that check that command level !Error parameter works fine.
//! @SYMTestExpectedResults Test case result is PASS.
//! @SYMTestActions         Call a command with an !Error expected. The command executes a function that sets the error using CDataWrapper::SetError().
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase034_obj
		COMMAND		!Error=-999 TestCase034_obj	SetError			TestCase034_obj_Error
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0071
