//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0105
//! @SYMTestCaseID          DT-TEF-TestBlock-0105
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that GetDataObjectL() returns error -1 if an empty name is provided
//! @SYMTestExpectedResults GetDataObjectL() must return -28 KBadName.
//! @SYMTestActions         1. Create a wrapper object
//!                         2. Call the GetDataObjectL() function passing a section that doesn't contain a key &quot;name&quot;
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		!Error=-28	DummyObj	GetDataObject			TestCase109_no_name
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0105
