//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0078
//! @SYMTestCaseID          DT-TEF-TestBlock-0078
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Mix new syntax with PREFIX and REMOVE_PREFIX commands
//! @SYMTestExpectedResults Test case completes without errors.
//! @SYMTestActions         Create a test case that has a test block, creates a wrapper object, calls a command
//!                         and uses PREFIX instruction before each other TEF instruction and REMOVE_PREFIX after each instruction.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0078
