//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0031
//! @SYMTestCaseID          DT-TEF-TestBlock-0031
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        COMMAND call with non existent function name.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Provide a non existent function name to a COMMAND instruction (assuming that
//!                         the overriden CDataWrapper::DoCommandL() returns EFalse in that case).
	PRINT This test case will be failed.
	START_TEST_BLOCK	te_RegBlockTestSuite 100 ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			ThereIsNoSuchFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0031
