//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite -SharedData

START_TESTCASE DT-TEF-TestBlock-0005
//! @SYMTestCaseID          DT-TEF-TestBlock-0005
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that START_TEST_BLOCK instruction's timeout parameter works fine if a server is loaded in shared mode.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Use a START_TEST_BLOCK with timeout 1 and inside the test block call a long delay.
	PRINT This test case will be failed.
	START_TEST_BLOCK	1 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		DELAY		10000000
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0005
