//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0016
//! @SYMTestCaseID          DT-TEF-TestBlock-0016
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        A test case where two START_TEST_BLOCK instructions are followed by one END_TEST_BLOCK (first block hasn't it's END_TEST_BLOCK).
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Create a START_TEST_BLOCK without a corresponding END_TEST_BLOCK. Inside
//!                         this block, add a valid test block with appropriate information. Do not have
//!                         any more START_TEST_BLOCK commands in the script, i.e. START_...
//!                         START_...END_.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase011_obj
		COMMAND		TestCase011_obj			DummyFunction
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase011_obj
		COMMAND		TestCase011_obja		DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0016
