//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite -SharedData

START_TESTCASE DT-TEF-TestBlock-0002
//! @SYMTestCaseID          DT-TEF-TestBlock-0002
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Try to restore an object without storing it in the previous block.
//! @SYMTestExpectedResults The test case must fail.
//! @SYMTestActions         1. Create a wrapper object in the first test block.
//!                         2. Call the object's command.
//!                         3. Use RESTORE_OBJECT instruction to restore the object.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase004_objb
		COMMAND		TestCase004_objb		DummyFunction
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		RESTORE_OBJECT	te_RegBlockTestWrapper	TestCase004_objb
		COMMAND		TestCase004_objb		DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0002
