//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0108
//! @SYMTestCaseID          DT-TEF-TestBlock-0108
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Use OUTSTANDING to without having any active objects.
//! @SYMTestExpectedResults The test case result must be PASS and the active object's work wasn't complete before OUTSTANDING call and it must be complete after the OUTSTANDING.
//! @SYMTestActions         1. Call OUTSTANDING with no arguments.
	START_TEST_BLOCK	20 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		OUTSTANDING
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0108
