//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

RUN_UTILS	MkDir		${SYSDRIVE}\testdata\
RUN_UTILS MkDir   ${SYSDRIVE}\testdata\configs\
START_TESTCASE DT-TEF-TestBlock-0079
//! @SYMTestCaseID          DT-TEF-TestBlock-0079
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Mix new syntax with RUN_UTILS commands
//! @SYMTestExpectedResults Test case completes without errors.
//! @SYMTestActions         Create a test case that has a test block, creates a wrapper object, calls a command
//!                         and mixes the functionality with the following actions:
//!                         1. Creates a directory using RUN_UTIL MkDir.
//!                         2. Copies a file using RUN_UTIL CopyFile.
//!                         3. Modifies the new file's permissions using RUN_UTIL MakeReadWrite.
//!                         4. Deletes the new file using RUN_UTIL DeleteFile.
	RUN_UTILS	CopyFile	${SYSDRIVE}\testdata\configs\file.txt	${SYSDRIVE}\testdata\configs\file_43.txt
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			DummyFunction
	END_TEST_BLOCK
	RUN_UTILS	MakeReadWrite	${SYSDRIVE}\testdata\configs\file_43.txt
END_TESTCASE DT-TEF-TestBlock-0079
RUN_UTILS	DeleteFile	${SYSDRIVE}\testdata\configs\file_43.txt
