//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0086
//! @SYMTestCaseID          DT-TEF-TestBlock-0086
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        !Heap TEF parameter on test block level with a negative value.
//! @SYMTestExpectedResults Test case result is PASS.
//! @SYMTestActions         Create a test block with !Heap parameter set to a negative value.
//!                         The test case must pass because values not between range 0x100 and 0x100000 must be set to a default value of 0x100000.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
	END_TEST_BLOCK		!Heap=-99999
END_TESTCASE DT-TEF-TestBlock-0086
