//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0066
//! @SYMTestCaseID          DT-TEF-TestBlock-0066
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Test that has a test block that calls a big number of commands.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         Create a valid START_TEST_BLOCK with appropriate parameters, and a
//!                         corresponding END_TEST_BLOCK keyword. Enter a lot of valid commands into the
//!                         block, i.e. attempt to create 200 objects and to perform 200 commands. The
//!                         contents of the block should be valid.
	START_TEST_BLOCK	te_RegBlockTestSuite 100 ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase014_obj
		COMMAND		TestCase014_obj			New				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value1
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value2
		COMMAND		TestCase014_obj			GetDataObject			TestCase014_obj_value2
		COMMAND		TestCase014_obj			Modify				TestCase014_obj_value1
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0066
