//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0055
//! @SYMTestCaseID          DT-TEF-TestBlock-0055
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        A test block expects a panic using !PanicString and !PanicCode parameters, but no panic happens.
//! @SYMTestExpectedResults The test case must fail.
//! @SYMTestActions         Use a block with !PanicString=MY_PANIC and !PanicCode=-999 parameters.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			DummyFunction
	END_TEST_BLOCK		!PanicString=MY_PANIC	!PanicCode=999
END_TESTCASE DT-TEF-TestBlock-0055
