//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0025
//! @SYMTestCaseID          DT-TEF-TestBlock-0025
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Call a command but do it with a !Result that has a numeric value
//! @SYMTestExpectedResults The test case must fail.
//! @SYMTestActions         1. Create a wrapper object
//!                         2. Use !Result=106 within the command call
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase032_obj
		COMMAND		!Result=999 TestCase032_obj	DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0025
