//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite -SharedData

START_TESTCASE DT-TEF-TestBlock-0004
//! @SYMTestCaseID          DT-TEF-TestBlock-0004
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that a active scheduler is not reused in the second block if SHARED_ACTIVE_SCHEDULER are not used.
//! @SYMTestExpectedResults The test case must fail.
//! @SYMTestActions         1. Create an active object (RTimer) in the first test block and
//!                         store both the data wrapper (containing the active object) and the active scheduler
//!                         2. In the second test block restore the wrapper and activate the active object.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		SHARED_ACTIVE_SCHEDULER
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase088_obj
		COMMAND		TestCase088_obj			AddActiveObjectToScheduler
		STORE		TestCase088_obj
		STORE_ACTIVE_SCHEDULER
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		SHARED_ACTIVE_SCHEDULER
		RESTORE_OBJECT	te_RegBlockTestWrapper	TestCase088_obj
		COMMAND		TestCase088_obj			ActivateActiveObject		TestCase088_obj
		OUTSTANDING
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0004
