//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0048
//! @SYMTestCaseID          DT-TEF-TestBlock-0048
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Use an active object without letting the active object to finish it's work.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Create an active object that needs some time to complete it's work but don't use any delay to let the active object to complete it's work.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase060_obj
		COMMAND		TestCase060_obj			AddActiveObjectToScheduler
		COMMAND		TestCase060_obj			ActivateActiveObject		TestCase060_obj
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0048
