//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0068
//! @SYMTestCaseID          DT-TEF-TestBlock-0068
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Create multiple wrapped objects making sure that the data from ini-file is read correctly.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         For a number of objects, wrap them such that the public APIs can be exposed
//!                         to the new framework for use by the script engine. Ensure that the wrappers
//!                         can read data from an .ini file during construction of the wrapped objects.
	START_TEST_BLOCK	te_RegBlockTestSuite 100 ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase017_obj
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase017_obja
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase017_objb
		COMMAND		TestCase017_obj			New				TestCase017_obj
		COMMAND		TestCase017_obj			GetDataObject			TestCase017_obj
		COMMAND		TestCase017_obja		New				TestCase017_obja
		COMMAND		TestCase017_obja		GetDataObject			TestCase017_obja
		COMMAND		TestCase017_objb		New				TestCase017_objb
		COMMAND		TestCase017_objb		GetDataObject			TestCase017_objb
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0068
