//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0041
//! @SYMTestCaseID          DT-TEF-TestBlock-0041
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that !Error on a block level uses last error code.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         Call a multiple commands with an !Error expected on the test block level. The first command executes
//!                         a function that sets the expected error code
//!                         using CDataWrapper::SetError(), but the next command set the error code to other than expected.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			SetError			TestCase072_obj_Error_999
		COMMAND		DummyObj			SetError			TestCase072_obj_Error_111
	END_TEST_BLOCK		!Error=-999
END_TESTCASE DT-TEF-TestBlock-0041
