//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0073
//! @SYMTestCaseID          DT-TEF-TestBlock-0073
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        A test that check that !PanicString TEF parameter works fine.
//! @SYMTestExpectedResults Test case result is PASS.
//! @SYMTestActions         Call a command with an !PanicString expected. The command executes a function that raises a panic with the given string.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase036_obj
		COMMAND		TestCase036_obj PanickingFunction		TestCase036_obj_Panic
	END_TEST_BLOCK		!PanicString=MY_PANIC
END_TESTCASE DT-TEF-TestBlock-0073
