//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0070
//! @SYMTestCaseID          DT-TEF-TestBlock-0070
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Create a test block and call DELAY command, check the interval.
//! @SYMTestExpectedResults The test completes without errors.
//! @SYMTestActions         1. Memorize current time using a command.
//!                         2. Call a DELAY instruction with 5 seconds parameter (5000000 microsceonds).
//!                         3. Check that the delay really was somewhere between 4 and 6 seconds.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper TestCase033_obj
		COMMAND		TestCase033_obj			StartTimer
		DELAY		5000000
		COMMAND		TestCase033_obj			CheckTimer			TestCase033_delay
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0070
