//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0040
//! @SYMTestCaseID          DT-TEF-TestBlock-0040
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        If a test block expects result PASS and several commands set the result to PASS but the last command sets the block result to FAIL then the test case must fail.
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         1. Use a test block without TEF parameters.
//!                         2. Call several commands that set the test block result to PASS.
//!                         3. Call a command that sets the test block result to FAIL.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Pass
		COMMAND		DummyObj		SetBlockResult			BlockResult_Fail
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0040
