//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0020
//! @SYMTestCaseID          DT-TEF-TestBlock-0020
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        The test case creates a wrapper object and then tries to call a command for an object that wasn't created (using wrong object name).
//! @SYMTestExpectedResults The test case result must be FAIL.
//! @SYMTestActions         1. Create a wrapper object with a name
//!                         2. Call a command providing another name
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase023_obj
		COMMAND		TestCase023_obja		DummyFunction
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0020
