//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0080
//! @SYMTestCaseID          DT-TEF-TestBlock-0080
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Use START_REPEAT and END_REPEAT constructions before and after a test block.
//! @SYMTestExpectedResults Test case must end with result PASS.
//! @SYMTestActions         See description.
	START_REPEAT	${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini TestCase044_counter	times_to_repeat
	END_REPEAT
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
			COMMAND		DummyObj		DummyFunction
	END_TEST_BLOCK
	START_REPEAT	${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini TestCase044_counter	times_to_repeat
	END_REPEAT
END_TESTCASE DT-TEF-TestBlock-0080
