//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0095
//! @SYMTestCaseID          DT-TEF-TestBlock-0095
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Check that DELAY also pauses the active scheduler.
//! @SYMTestExpectedResults Check that the active object was also paused using the DELAY
//! @SYMTestActions         Create a test block, create an active object (RTimer) in the test block and activate it. Call DELAY
//!                         command for a longer then the active object requires to finish it's work. And check that the
//!                         active object's work is not complete.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase090_obj
		COMMAND		TestCase090_obj			AddActiveObjectToScheduler
		COMMAND		TestCase090_obj			ActivateActiveObject		TestCase090_obj
		DELAY		200000
		COMMAND		TestCase090_obj			CheckActiveObjectWorkIsComplete		TestCase090_must_be_complete_false
		OUTSTANDING
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0095
