//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

PAUSE
START_TESTCASE DT-TEF-TestBlock-0075
//! @SYMTestCaseID          DT-TEF-TestBlock-0075
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Mix new syntax with PAUSE command.
//! @SYMTestExpectedResults Test case completes without errors
//! @SYMTestActions         Create a test case that has a test block, creates a wrapper object, calls a command
//!                         and uses PAUSE instruction after each other TEF instruction.
	PAUSE
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			DummyFunction
	END_TEST_BLOCK
	PAUSE
END_TESTCASE DT-TEF-TestBlock-0075
PAUSE
