//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0112
//! @SYMTestCaseID          DT-TEF-TestBlock-0112
//! @SYMCreationDate        10-11-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This case from defect DPDEF129608. when panic or leave happened with number -16(KErrServerBusy), testexecute will retry again.
//!                         two scenario:
//!                         1. In some situation, test server really busy, testexecute should retry.
//!                         2. On other wise, test server execute some test, this test require a server which busy. test server should notice the server busy and retry.
//!                         
//!                         So this test case only test server leave(panic) with -16.this not a really test server busy..So the test should go on next test without retry current.
//!                         Both shareddata and non-shareddata should act same.
//! @SYMTestExpectedResults test block pass, panic happens with -16
//! @SYMTestActions         1.read ini test number;
//!                         2.panic with the number.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\TestData\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	serverbusy_panic-016
		COMMAND		serverbusy_panic-016  PanickingFunction		serverbusy_panic-016_obj_Panic
	END_TEST_BLOCK		!PanicCode=-16
END_TESTCASE DT-TEF-TestBlock-0112
