//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite -SharedData

START_TESTCASE DT-TEF-TestBlock-0003
//! @SYMTestCaseID          DT-TEF-TestBlock-0003
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Store an object in a first block, restore it in the second but without consequent storing. Make sure that the third block, that tries to restore the object fails.
//! @SYMTestExpectedResults The test case must fail.
//! @SYMTestActions         1. Create a wrapper object in the first test block.
//!                         2. Call the object's command.
//!                         3. Store the object.
//!                         4. Use RESTORE_OBJECT instruction to restore the object in the second block.
//!                         5. Call the object's command.
//!                         6. Use RESTORE_OBJECT instruction to restore the object in the third block.
	PRINT This test case will be failed.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObject
		COMMAND		DummyObject			DummyFunction
		STORE		DummyObject
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		RESTORE_OBJECT	te_RegBlockTestWrapper	DummyObject
		COMMAND		DummyObject			DummyFunction
	END_TEST_BLOCK
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		RESTORE_OBJECT	te_RegBlockTestWrapper	DummyObject
	END_TEST_BLOCK
END_TESTCASE DT-TEF-TestBlock-0003
