//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

START_TESTCASE DT-TEF-TestBlock-0114
//! @SYMTestCaseID          DT-TEF-TestBlock-0114
//! @SYMCreationDate        10-11-2008
//! @SYMAuthor              extshuohuang
//! @SYMTestCaseDesc        this test case form DPDEF129807. when panic string to long the testexecute can't handle the long panic sting.
//!                         So adding this test case to test.
//! @SYMTestExpectedResults the panic happened but the panic string was cut-off to 16 bytes by User::Panic().
//!                         in the script, expecting a long panic string. so this 2 string never match.
//!                         so the test case should fail.
//! @SYMTestActions         1. read panci string for ini.
//!                         2. do panic.
	PRINT this test case should fail. Keep the panic string length to 16 charactersor less. Please Refer to User::Panic() in SDL for more information.
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase0114_obj
		COMMAND		TestCase0114_obj PanickingFunction		TestCase0114_obj_Panic
	END_TEST_BLOCK		!PanicString="DoMediaClockStoppedState: Mutex Unheld" !PanicCode=22
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	TestCase037_obj
		COMMAND		TestCase0114_obj PanickingFunction		TestCase0114_obj_Panic
	END_TEST_BLOCK		!PanicCode=22 !PanicString="DoMediaClockStoppedState: Mutex Unheld"
END_TESTCASE DT-TEF-TestBlock-0114