//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SERVER te_RegBlockTestSuite 

PRINT	A text is printed (1 of 4).
START_TESTCASE DT-TEF-TestBlock-0077
//! @SYMTestCaseID          DT-TEF-TestBlock-0077
//! @SYMCreationDate        03-07-2008
//! @SYMAuthor              DavidZhang
//! @SYMTestType            CT
//! @SYMTestPriority        Medium
//! @SYMTestCaseDesc        Mix new syntax with PRINT command.
//! @SYMTestExpectedResults Test case completes without errors.
//! @SYMTestActions         Create a test case that has a test block, creates a wrapper object, calls a command
//!                         and uses PRINT instruction after each other TEF instruction.
	PRINT	A text is printed (2 of 4).
	START_TEST_BLOCK	100 te_RegBlockTestSuite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
		CREATE_OBJECT	te_RegBlockTestWrapper	DummyObj
		COMMAND		DummyObj			DummyFunction
	END_TEST_BLOCK
	PRINT	A text is printed (3 of 4).
END_TESTCASE DT-TEF-TestBlock-0077
PRINT	A text is printed (4 of 4).
