//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\
CopyFile z:\testdata\scripts\dt-tef-testblock-*.script	${SYSDRIVE}\testdata\scripts\dt-tef-testblock-*.script

CopyFile z:\testdata\configs\te_RegBlockTestSuite.ini	${SYSDRIVE}\testdata\configs\te_regblocktestsuite.ini
CopyFile z:\testdata\configs\file.txt	${SYSDRIVE}\testdata\configs\file.txt

MakeReadWrite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
REMOVE_PREFIX 

RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0001.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0002.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0003.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0004.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0005.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0006.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0007.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0008.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0009.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0010.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0011.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0012.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0013.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0014.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0015.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0016.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0017.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0018.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0019.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0020.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0021.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0022.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0023.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0024.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0025.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0026.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0027.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0028.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0029.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0030.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0031.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0032.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0033.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0034.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0035.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0036.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0037.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0038.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0039.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0040.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0041.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0042.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0043.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0044.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0045.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0046.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0047.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0048.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0049.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0050.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0051.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0052.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0053.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0054.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0055.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0056.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0057.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0058.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0059.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0060.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0061.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0062.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0063.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0064.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0065.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0066.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0067.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0068.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0069.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0070.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0071.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0072.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0073.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0074.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0075.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0076.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0077.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0078.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0079.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0080.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0081.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0082.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0083.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0084.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0085.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0086.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0087.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0088.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0089.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0090.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0091.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0092.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0093.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0094.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0095.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0096.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0097.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0098.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0099.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0100.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0101.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0102.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0103.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0104.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0105.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0106.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0107.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0108.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0109.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0110.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0111.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0112.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0113.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0114.script
RUN_SCRIPT ${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0115.script
