//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\dt-tef-testblock-*.script	${SYSDRIVE}\testdata\scripts\dt-tef-testblock-*.script

CopyFile z:\testdata\configs\te_RegBlockTestSuite.ini	${SYSDRIVE}\testdata\configs\te_regblocktestsuite.ini
CopyFile z:\testdata\configs\file.txt	${SYSDRIVE}\testdata\configs\file.txt

MakeReadWrite ${SYSDRIVE}\testdata\configs\te_RegBlockTestSuite.ini
REMOVE_PREFIX 

PREFIX RUN_PROGRAM 50 testexecute
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0005.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0006.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0007.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0008.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0009.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0010.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0011.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0012.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0013.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0014.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0015.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0016.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0017.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0018.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0019.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0020.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0021.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0022.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0023.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0024.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0025.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0026.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0027.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0028.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0029.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0030.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0031.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0032.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0033.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0034.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0035.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0036.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0037.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0038.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0039.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0040.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0041.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0042.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0043.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0044.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0045.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0046.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0047.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0048.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0049.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0050.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0051.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0052.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0053.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0054.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0055.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0056.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0057.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0058.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0059.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0060.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0061.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0062.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0063.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0064.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0065.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0066.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0067.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0068.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0069.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0070.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0071.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0072.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0073.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0074.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0075.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0076.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0077.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0078.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0079.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0080.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0081.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0082.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0083.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0084.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0085.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0086.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0087.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0088.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0089.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0090.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0091.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0092.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0093.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0094.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0095.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0096.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0097.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0098.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0099.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0100.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0101.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0102.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0103.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0104.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0105.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0106.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0107.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0108.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0109.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0110.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0111.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0112.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0113.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0114.script
${SYSDRIVE}\testdata\scripts\dt-tef-testblock-0115.script
REMOVE_PREFIX
