# emn1_0stringdict00tagtable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Emn1_0StringDict00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EEmn 						emn
# //////////////////////////////////////////////////////////////////////
!// For XML
EUri						-//WAPFORUM//DTD EMN 1.0//EN
!// For WBXML
EPublicId					D~0
EFormalPublicId				-//WAPFORUM//DTD EMN 1.0//EN
