# emn1_0stringdict00attributetable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Short String table
#
stringtable Emn1_0StringDict00AttributeTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
EMailbox 		mailbox
ETimestamp 		timestamp
