//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_UnitTest
START_TESTCASE DT-TEF-Unit-0001
//! @SYMTestCaseID          DT-TEF-Unit-0001
//! @SYMCreationDate        01-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestCaseDesc        Test CActiveTestFixture class. Test read/write configration APIs.
//! @SYMTestExpectedResults This test case test ini config APIs.
//!                         Each API should pass then the test case will pass.
//!                         if one API fails all test case will fail.
RUN_TEST_STEP 100 TEF_UnitTest TEFUnit.CTEFActiveFixtureUT.TestCTestConfig ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini TEFUnitSection1	
END_TESTCASE DT-TEF-Unit-0001