//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_UnitTest

START_TESTCASE DT-TEF-Unit-0002
//! @SYMTestCaseID          DT-TEF-Unit-0002
//! @SYMCreationDate        01-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        Test CActiveTestFixture class. Test read/write configration APIs.
//!                         This is negtive test case.
//! @SYMTestExpectedResults The step not provides config file seciton. so test case should fail at first api call WriteInt.
//!                         the last test will set the whole test step fail compare the return value.
PRINT this test case should be fail.
RUN_TEST_STEP 100 TEF_UnitTest TEFUnit.CTEFActiveFixtureUT.TestCTestConfig_Negtive ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini 
END_TESTCASE DT-TEF-Unit-0002