//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_UnitTest

START_TESTCASE DT-TEF-Unit-0003
//! @SYMTestCaseID          DT-TEF-Unit-0003
//! @SYMCreationDate        01-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This test case test Unit step time out situation.
//! @SYMTestExpectedResults this test case should not time out. step will finish with in 200 seconds. the test case result is pass.
RUN_TEST_STEP 100 TEF_UnitTest TEFUnit.CTEFActiveFixtureUT.TestUnitTimeout ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini 	
END_TESTCASE DT-TEF-Unit-0003
