//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE	TEF_UnitTest

START_TESTCASE DT-TEF-Unit-0004
//! @SYMTestCaseID          DT-TEF-Unit-0004
//! @SYMCreationDate        01-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        High
//! @SYMTestCaseDesc        This test case test Unit step time out situation.
//! @SYMTestExpectedResults This test case should fail. Because the test only enable 1 second.
PRINT this test case should be fail. Designed to time out.
RUN_TEST_STEP 1 TEF_UnitTest TEFUnit.CTEFActiveFixtureUT.TestUnitTimeout_Negtive ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini TEFUnitSection1
END_TESTCASE DT-TEF-Unit-0004
