//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

PRINT Run test case(s) for suite TEF_UnitTest
PREFIX RUN_UTILS
MkDir ${SYSDRIVE}\testdata\
MkDir ${SYSDRIVE}\testdata\scripts\
MkDir ${SYSDRIVE}\testdata\configs\

CopyFile z:\testdata\scripts\te_regunittest.script ${SYSDRIVE}\testdata\scripts\te_regunittest.script
CopyFile 	z:\testdata\scripts\dt-tef-unit-*.script	 	${SYSDRIVE}\testdata\scripts\dt-tef-unit-*.script 

CopyFile z:\testdata\configs\ReadWriteConfig.ini ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini
MakeReadWrite ${SYSDRIVE}\testdata\configs\ReadWriteConfig.ini
REMOVE_PREFIX

PREFIX RUN_PROGRAM 50 testexecute
${SYSDRIVE}\testdata\scripts\dt-tef-unit-0001.script
${SYSDRIVE}\testdata\scripts\dt-tef-unit-0002.script
${SYSDRIVE}\testdata\scripts\dt-tef-unit-0003.script
${SYSDRIVE}\testdata\scripts\dt-tef-unit-0004.script
${SYSDRIVE}\testdata\scripts\dt-tef-unit-0005.script
REMOVE_PREFIX
