//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run all def130695_ Suite Tests

LOAD_SUITE def130695_Suite

START_TESTCASE BASESRVCS-XML-CT-4925 // Libmxl2 vulnerability test
//!@SYMTestCaseID                BASESRVCS-XML-CT-4925
//!@SYMTestCaseDesc              Libxml2 -- vulnerabilities from Debian Security Advisory : XmlBufferResize( ) in libxml2_tree.c.
//!@SYMTestPriority              Normal
//!@SYMTestActions               Pass NULL to XmlBufferResize( )
//!@SYMTestExpectedResults       The API should recognize the NULL and report back in case of such vulnerable situations.
//!@SYMDEF                       DEF130695
RUN_TEST_STEP 100 def130695_Suite def130695_Step1 c:\testdata\configs\def130695_Suite.ini Section0
END_TESTCASE BASESRVCS-XML-CT-4925 // Libmxl2 vulnerability test

START_TESTCASE BASESRVCS-XML-CT-4926 // Libmxl2 vulnerability test
//!@SYMTestCaseID                BASESRVCS-XML-CT-4926
//!@SYMTestCaseDesc              Libxml2 -- vulnerabilities from Debian Security Advisory : XmlSax2Characters( ) in libxml2_tree.c.
//!@SYMTestPriority              Normal
//!@SYMTestActions               Pass NULL to XmlSax2Characters( )
//!@SYMTestExpectedResults       The API should recognize the NULL and report back in case of such vulnerable situations.
//!@SYMDEF                       DEF130695
RUN_TEST_STEP 100 def130695_Suite def130695_Step2 c:\testdata\configs\def130695_Suite.ini Section1
END_TESTCASE BASESRVCS-XML-CT-4926 // Libmxl2 vulnerability test

PRINT Complate_def130695__Tests
