// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Run XML xmlengdomutils_tef
LOAD_SUITE xmlengdomutils_tef
DELAY 500
START_TESTCASE BASESRVCS-XML-CT-4935
//
//! @SYMTestCaseID BASESRVCS-XML-CT-4935
//! @SYMTestCaseDesc Tests the APIs to improve the code coverage
//! @SYMPREQ PREQ2051
//! @SYMTestPriority High
//! @SYMTestActions The following API is tested for code coverage
//! TXmlEngElement::CreateElementL TXmlEngDocumentFragment::CreateDocumentFragmentL
//!	TDomUtils::XmlEngRenameElementL TXmlEngElement::ReplaceWithL
//! @SYMTestExpectedResults EPass
	RUN_TEST_STEP 100 xmlengdomutils_tef XmlEngDomUtilStep1
	RUN_TEST_STEP 100 xmlengdomutils_tef XmlEngNodeTestSetValue
	RUN_TEST_STEP 100 xmlengdomutils_tef XmlEngNodeTestReplaceWith
	RUN_TEST_STEP 100 xmlengdomutils_tef XmlEngDocumentCreateDocumentFragment
END_TESTCASE BASESRVCS-XML-CT-4935