//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-SelTestCase-0001
PRINT run DT-TEF-SelTestCase-0001
END_TESTCASE DT-TEF-SelTestCase-0001

START_TESTCASE DT-TEF-SelTestCase-0002
PRINT run DT-TEF-SelTestCase-0002
END_TESTCASE DT-TEF-SelTestCase-0002

START_TESTCASE DT-TEF-SelTestCase-0003
PRINT run DT-TEF-SelTestCase-0003
END_TESTCASE DT-TEF-SelTestCase-0003

START_TESTCASE DT-TEF-SelTestCase-0004
PRINT run DT-TEF-SelTestCase-0004
END_TESTCASE DT-TEF-SelTestCase-0004

START_TESTCASE DT-TEF-SelTestCase-0005
PRINT run DT-TEF-SelTestCase-0005
END_TESTCASE DT-TEF-SelTestCase-0005

START_TESTCASE DT-TEF-SelTestCase-0006
PRINT run DT-TEF-SelTestCase-0006
END_TESTCASE DT-TEF-SelTestCase-0006

START_TESTCASE DT-TEF-SelTestCase-0007
PRINT run DT-TEF-SelTestCase-0007
END_TESTCASE DT-TEF-SelTestCase-0007

START_TESTCASE DT-TEF-SelTestCase-0008
PRINT run DT-TEF-SelTestCase-0008
END_TESTCASE DT-TEF-SelTestCase-0008

START_TESTCASE DT-TEF-SelTestCase-0009
PRINT run DT-TEF-SelTestCase-0009
END_TESTCASE DT-TEF-SelTestCase-0009

START_TESTCASE DT-TEF-SelTestCase-0010
PRINT run DT-TEF-SelTestCase-0010
END_TESTCASE DT-TEF-SelTestCase-0010

START_TESTCASE DT-TEF-SelTestCase-0011
PRINT run DT-TEF-SelTestCase-0011
END_TESTCASE DT-TEF-SelTestCase-0011

START_TESTCASE DT-TEF-SelTestCase-0012
PRINT run DT-TEF-SelTestCase-0012
END_TESTCASE DT-TEF-SelTestCase-0012

START_TESTCASE DT-TEF-SelTestCase-0013
PRINT run DT-TEF-SelTestCase-0013
END_TESTCASE DT-TEF-SelTestCase-0013

START_TESTCASE DT-TEF-SelTestCase-0014
PRINT run DT-TEF-SelTestCase-0014
END_TESTCASE DT-TEF-SelTestCase-0014

START_TESTCASE DT-TEF-SelTestCase-0015
PRINT run DT-TEF-SelTestCase-0015
END_TESTCASE DT-TEF-SelTestCase-0015