//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-AnotherTestCase-0001
PRINT run DT-TEF-AnotherTestCase-0001
END_TESTCASE DT-TEF-AnotherTestCase-0001

RUN_SCRIPT	${SYSDRIVE}\testdata\scripts\te_regseltestcase.script

START_TESTCASE DT-TEF-AnotherTestCase-0002
PRINT run DT-TEF-AnotherTestCase-0002
END_TESTCASE DT-TEF-AnotherTestCase-0002

START_TESTCASE DT-TEF-SelTestCase-0003
PRINT run DT-TEF-SelTestCase-0003
END_TESTCASE DT-TEF-SelTestCase-0003

START_TESTCASE DT-TEF-AnotherTestCase-0003
PRINT run DT-TEF-AnotherTestCase-0003
END_TESTCASE DT-TEF-AnotherTestCase-0003

START_TESTCASE DT-TEF-AnotherTestCase-0004
PRINT run DT-TEF-AnotherTestCase-0004
END_TESTCASE DT-TEF-AnotherTestCase-0004

START_TESTCASE DT-TEF-AnotherTestCase-0005
PRINT run DT-TEF-AnotherTestCase-0005
END_TESTCASE DT-TEF-AnotherTestCase-0005

START_TESTCASE DT-TEF-SelTestCase-0005
PRINT run DT-TEF-SelTestCase-0005
END_TESTCASE DT-TEF-SelTestCase-0005

START_TESTCASE DT-TEF-AnotherTestCase-0006
PRINT run DT-TEF-AnotherTestCase-0006
END_TESTCASE DT-TEF-AnotherTestCase-0006

START_TESTCASE DT-TEF-AnotherTestCase-0007
PRINT run DT-TEF-AnotherTestCase-0007
END_TESTCASE DT-TEF-AnotherTestCase-0007

