# syncml1_1opaquecodepage00tagtable.st
#
# Copyright (c) Symbian Software Ltd 2003 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Please see the StringDictionary HowTo more information on this file.
#
stringtable Syncml1_1OpaqueCodePage00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
ECTCap			CTCap
ECTType			CTType
EDataStore			DataStore
EDataType			DataType
EDevID			DevID
EDevInf			DevInf
EDevTyp			DevTyp
EDisplayName		DisplayName
EDSMem			DSMem
EExt				Ext
EFwV				FwV
EHwV				HwV
EMan				Man
EMaxGUIDSize		MaxGUIDSize
EMaxID			MaxID
EMaxMem			MaxMem
EMod				Mod
EOEM				OEM
EParamName			ParamName
EPropName			PropName
ERx				Rx
ERxPref			Rx-Pref
ESharedMem 			SharedMem
ESize				Size
ESourceRef			SourceRef
ESwV				SwV
ESyncCap			SyncCap
ESyncType			SyncType
ETx				Tx
ETxPref			Tx-Pref
EValEnum			ValEnum
EVerCT			VerCT
EVerDTD			VerDTD
EXnam				Xnam
EXval				Xval
EUTC				UTC
ESupportNumberOfChanges	SupportNumberOfChanges
ESupportLargeObjs		SupportLargeObjs
# //////////////////////////////////////////////////////////////////////
!// For XML
EUrn						syncml:devinf
!// For WBXML
EPublicId					FD2~0
EFormalPublicId				-//SYNCML//DTD DevInf 1.1//EN~0