# syncml1_2codepage01tagtable.st
#
# Copyright (c) Symbian Software Ltd 2005 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Please see the StringDictionary HowTo more information on this file.
#
stringtable Syncml1_2CodePage01TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 01
EAnchor	Anchor
EEMI		EMI
EFormat	Format
EFreeID	FreeID
EFreeMem	FreeMem
ELast		Last
EMark		Mark
EMaxMsgSize	MaxMsgSize
EMem		Mem
EMetInf	MetInf
ENext		Next
ENextNonce	NextNonce
ESharedMem	SharedMem
ESize		Size
EType		Type
EVersion	Version
EMaxObjSize	MaxObjSize
EFieldLevel	FieldLevel
# //////////////////////////////////////////////////////////////////////
!// For XML
EUrn						syncml:metinf
!// For WBXML
EPublicId					1201~1
EFormalPublicId				-//SYNCML//DTD SyncML 1.2//EN~1
