# syncml1_2opaquecodepage00tagtable.st
#
# Copyright (c) Symbian Software Ltd 2005 - 2007. All rights reserved.
#
# NOTE: For WBXML - Direct correlation on ordering of tag entries to the tag values 
#       the parser defines
# No empty lines allowed either
#
# Please see the StringDictionary HowTo more information on this file.
#
stringtable Syncml1_2OpaqueCodePage00TagTable
# //////////////////////////////////////////////////////////////////////
!// Element names
!// CodePage 00
ECTCap			CTCap
ECTType			CTType
EDataStore			DataStore
EDataType			DataType
EDevID			DevID
EDevInf			DevInf
EDevTyp			DevTyp
EDisplayName		DisplayName
EDSMem			DSMem
EExt				Ext
EFwV				FwV
EHwV				HwV
EMan				Man
EMaxGUIDSize		MaxGUIDSize
EMaxID			MaxID
EMaxMem			MaxMem
EMod				Mod
EOEM				OEM
EParamName			ParamName
EPropName			PropName
ERx				Rx
ERxPref			Rx-Pref
ESharedMem 			SharedMem
EMaxSize			MaxSize
ESourceRef			SourceRef
ESwV				SwV
ESyncCap			SyncCap
ESyncType			SyncType
ETx				Tx
ETxPref			Tx-Pref
EValEnum			ValEnum
EVerCT			VerCT
EVerDTD			VerDTD
EXnam				XNam
EXval				XVal
EUTC				UTC
ESupportNumberOfChanges	SupportNumberOfChanges
ESupportLargeObjs		SupportLargeObjs
EProperty			Property
EPropParam			PropParam
EMaxOccur			MaxOccur
ENoTruncate			NoTruncate
EFilterRx			Filter-Rx
EFilterCap			FilterCap
EFilterKeyword		FilterKeyword
EFieldLevel			FieldLevel
ESupportHierarchicalSync	SupportHierarchicalSync
# //////////////////////////////////////////////////////////////////////
!// For XML
EUrn						syncml:devinf
!// For WBXML
EPublicId					FD4~0
EFormalPublicId				-//SYNCML//DTD DevInf 1.2//EN~0