// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

PRINT Loading suite texmlparser2
LOAD_SUITE texmlparser2
DELAY 500

//
//! @SYMTestCaseID	BASESRVCS-XML-CT-4928
//! @SYMTestCaseDesc	Tests the APIs under different memory conditions
//! @SYMPREQ		PREQ2051
//! @SYMTestPriority	High
//! @SYMTestActions	The following APIs are testing under various
//!			memory conditions:
//!			SetProcessorChainL, DisableFeature, EnableFeature
//! @SYMTestExpectedResults	EPass
//

START_TESTCASE BASESRVCS-XML-CT-4928
	RUN_TEST_STEP 100 texmlparser2 XmlParser2SetContentSink
	RUN_TEST_STEP 100 texmlparser2 XmlParser2OOMTests
	RUN_TEST_STEP 100 texmlparser2 XmlParser2OOMTests2
	RUN_TEST_STEP 100 texmlparser2 XmlParser2OOMTests3
	RUN_TEST_STEP 100 texmlparser2 XmlParser2OOMTests4
END_TESTCASE BASESRVCS-XML-CT-4928