//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

START_TESTCASE DT-TEF-Utilities-0003
//! @SYMTestCaseID          DT-TEF-Utilities-0003
//! @SYMCreationDate        05-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        Low
//! @SYMTestCaseDesc        this test case test formate driver utility.
//! @SYMTestExpectedResults should be pass on emulater.

PRINT Test Step to format a disk drive mentioned in the ini test data
LOAD_SUITE TEFUtilityServer
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveQF
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveHD
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveLD
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveFF
PRINT End of FormatDrive Test Step

END_TESTCASE DT-TEF-Utilities-0003
