//
// Copyright (c) 2005-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//

LOAD_SUITE TEFUtilityServer
START_TESTCASE DT-TEF-Utilities-0004
//! @SYMTestCaseID          DT-TEF-Utilities-0004
//! @SYMCreationDate        05-09-2008
//! @SYMAuthor              extShuoHuang
//! @SYMTestPriority        Low
//! @SYMTestCaseDesc        this test case test formate driver utility.
//! @SYMTestExpectedResults should be fail. because the parameter is err.
PRINT should be fail.
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveERRORLetter
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveERRORLetter2
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveERRORformat
RUN_TEST_STEP	1000	TEFUtilityServer	FormatDrive	${SYSDRIVE}\testdata\configs\te_regutilitiesut.ini	formatdriveMutiLetter
END_TESTCASE DT-TEF-Utilities-0004
